package:
  name: click
  version: 8.2.1
source:
  url: https://files.pythonhosted.org/packages/85/32/10bb5764d90a8eee674e9dc6f4db6a0ab47c8c4d0d83c27f7c39ac415a4d/click-8.2.1-py3-none-any.whl
  sha256: 61a3265b914e850b85317d0b3109c7f8cd35a670f963866005d6ef1d5175a12b
test:
  imports:
    - click
about:
  home: https://palletsprojects.com/p/click/
  PyPI: https://pypi.org/project/click
  summary: Composable command line interface toolkit
  license: BSD-3-Clause
