package:
  name: click
  version: 8.3.1
source:
  url: https://files.pythonhosted.org/packages/98/78/01c019cdb5d6498122777c1a43056ebb3ebfeef2076d9d026bfe15583b2b/click-8.3.1-py3-none-any.whl
  sha256: 981153a64e25f12d547d3426c367a4857371575ee7ad18df2a6183ab0545b2a6
test:
  imports:
    - click
about:
  home: https://palletsprojects.com/p/click/
  PyPI: https://pypi.org/project/click
  summary: Composable command line interface toolkit
  license: BSD-3-Clause
