package:
  name: click
  version: 8.3.0
source:
  url: https://files.pythonhosted.org/packages/db/d3/9dcc0f5797f070ec8edf30fbadfb200e71d9db6b84d211e3b2085a7589a0/click-8.3.0-py3-none-any.whl
  sha256: 9b9f285302c6e3064f4330c05f05b81945b2a39544279343e6e7c5f27a9baddc
test:
  imports:
    - click
about:
  home: https://palletsprojects.com/p/click/
  PyPI: https://pypi.org/project/click
  summary: Composable command line interface toolkit
  license: BSD-3-Clause
