package:
  name: pynacl
  version: 1.6.0
  top-level:
    - nacl
source:
  url: https://files.pythonhosted.org/packages/06/c6/a3124dee667a423f2c637cfd262a54d67d8ccf3e160f3c50f622a85b7723/pynacl-1.6.0.tar.gz
  sha256: cb36deafe6e2bce3b286e5d1f3e1c246e0ccdb8808ddb4550bb2792f2df298f2
requirements:
  run:
    - cffi
  host:
    - cffi
about:
  home: https://github.com/pyca/pynacl/
  PyPI: https://pypi.org/project/pynacl
  summary: Python binding to the Networking and Cryptography (NaCl) library
  license: Apache-2.0
