package:
  name: lz4
  version: 4.4.5
  top-level:
    - lz4
source:
  url: https://files.pythonhosted.org/packages/source/l/lz4/lz4-4.4.5.tar.gz
  sha256: 5f0b9e53c1e82e88c10d7c180069363980136b9d7a8306c4dca4f760d60c39f0
about:
  home: https://github.com/python-lz4/python-lz4
  PyPI: https://pypi.org/project/lz4
  summary: LZ4 Bindings for Python
  license: BSD
extra:
  recipe-maintainers:
    - greateggsgreg
