package:
  name: regex
  version: 2026.3.32
  tag:
    - core
    - min-scipy-stack
  top-level:
    - regex
source:
  sha256: f1574566457161678297a116fa5d1556c5a4159d64c5ff7c760e7c564bf66f16
  url: https://files.pythonhosted.org/packages/source/r/regex/regex-2026.3.32.tar.gz
about:
  home: https://github.com/mrabarnett/mrab-regex
  PyPI: https://pypi.org/project/regex
  summary: Alternative regular expression module, to replace re.
  license: Apache-2.0
