package:
  name: pytaglib
  version: 3.2.0
  top-level:
    - taglib

requirements:
  host:
    - libtaglib

build:
  vendor-sharedlib: true
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib

source:
  url: https://files.pythonhosted.org/packages/source/p/pytaglib/pytaglib-3.2.0.tar.gz
  sha256: 964e32e86edcda107eb3821dd4ca226de04f7f0f99bb4c18737e138b4ed3313f

about:
  license: GPL-3.0

extra:
  recipe-maintainers:
    - swnf
