package:
  name: clarabel
  version: 0.11.0
  tag:
    - rust
  top-level:
    - clarabel
source:
  url: https://files.pythonhosted.org/packages/source/c/clarabel/clarabel-0.11.0.tar.gz
  sha256: 7a8ee6fe74eb7e7ba457b664e312e6953dec4bd1651d4725f5b5bcff5ef4dbc1
  patches:
    - patches/0001-Update-faer-version.patch
about:
  home: https://github.com/oxfordcontrol/Clarabel.rs
  PyPI: https://pypi.org/project/clarabel
  summary: Clarabel Conic Interior Point Solver for Rust / Python
  license: Apache-2.0
requirements:
  run:
    # Dependencies that are needed to run the package
    - numpy
    - scipy
  executable:
    - rustup
  constraint:
    - maturin < 1.8
extra:
  recipe-maintainers:
    - phschiele
