package:
  name: clarabel
  version: 0.11.1
  tag:
    - rust
  top-level:
    - clarabel
source:
  url: https://files.pythonhosted.org/packages/source/c/clarabel/clarabel-0.11.1.tar.gz
  sha256: e7c41c47f0e59aeab99aefff9e58af4a8753ee5269bbeecbd5526fc6f41b9598
  patches:
    - patches/0001-Update-faer-version.patch
about:
  home: https://github.com/oxfordcontrol/Clarabel.rs
  PyPI: https://pypi.org/project/clarabel
  summary: Clarabel Conic Interior Point Solver for Rust / Python
  license: Apache-2.0
requirements:
  run:
    # Dependencies that are needed to run the package
    - numpy
    - scipy
  executable:
    - rustup
extra:
  recipe-maintainers:
    - phschiele
