package:
  name: libiconv
  version: "1.16"
  tag:
    - library
    - static_library
source:
  url: https://github.com/ryanking13/lib-mirror/releases/download/1.0.0/libiconv-1.16.tar.gz
  sha256: e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04

build:
  type: static_library
  script: |
    emconfigure ./configure \
       CFLAGS="-fPIC" \
       --disable-dependency-tracking \
       --disable-shared \
       --prefix=${WASM_LIBRARY_DIR}

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
about:
  home: https://www.gnu.org/software/libiconv/
  license: LGPL-2.1
