package:
  name: pyproj
  version: 3.7.2
  top-level:
    - pyproj
source:
  url: https://files.pythonhosted.org/packages/04/90/67bd7260b4ea9b8b20b4f58afef6c223ecb3abf368eb4ec5bc2cdef81b49/pyproj-3.7.2.tar.gz
  sha256: 39a0cf1ecc7e282d1d30f36594ebd55c9fae1fda8a2622cee5d100430628f88c

requirements:
  host:
    - libproj
  run:
    - certifi

build:
  script: |
    export PROJ_VERSION=9.6.2
    export PROJ_DIR=${WASM_LIBRARY_DIR}
    export PROJ_INCDIR=${WASM_LIBRARY_DIR}/include
    export PROJ_LIBDIR=${WASM_LIBRARY_DIR}/lib
    export PROJ_WHEEL=1
    mkdir -p pyproj/proj_dir/share
    cp -r ${WASM_LIBRARY_DIR}/share/proj pyproj/proj_dir/share
test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  PyPI: https://pypi.org/project/pyproj/
  summary:
    Python interface to PROJ (cartographic projections and coordinate transformations
    library)
  license: MIT
