package:
  name: requests
  version: 2.32.4
  top-level:
    - requests
source:
  url: https://files.pythonhosted.org/packages/py3/r/requests/requests-2.32.4-py3-none-any.whl
  sha256: 27babd3cda2a6d50b30443204ee89830707d396671944c998b5975b031ac2b2c
requirements:
  run:
    - charset-normalizer
    - idna
    - urllib3
    - certifi
test:
  imports:
    - requests
about:
  home: https://requests.readthedocs.io
  PyPI: https://pypi.org/project/requests
  summary: Python HTTP for Humans.
  license: Apache-2.0
