package:
  name: sisl
  version: 0.16.2
  top-level:
  - sisl_toolbox
  - sisl
source:
  url: https://files.pythonhosted.org/packages/source/s/sisl/sisl-0.16.2.tar.gz
  sha256: 21cc2575ca1d3dc7821757765bc84dbe288d11e1216618216c56fd759aecb79d
about:
  home: https://github.com/zerothi/sisl
  PyPI: https://pypi.org/project/sisl
  summary: Manipulation and post-processing of DFT output and creating 
    tight-binding models for NEGF transport
  license: MPL-2.0

requirements:
  host:
    - numpy
    - pyparsing
  run:
    - pyparsing
    - numpy
    - scipy
    - tqdm
    - xarray
    - pandas
    - matplotlib

build:
  script: |
    export CMAKE_ARGS="-DWITH_FORTRAN=OFF"

extra:
  recipe-maintainers:
  - zerothi
