package:
  name: sisl
  version: 0.16.4
  top-level:
    - sisl_toolbox
    - sisl
source:
  url: https://files.pythonhosted.org/packages/source/s/sisl/sisl-0.16.4.tar.gz
  sha256: bba5fd45a6286d20eabd1232ea83d830d63f343c6212021034c31d53dee928a3
about:
  home: https://github.com/zerothi/sisl
  PyPI: https://pypi.org/project/sisl
  summary: Manipulation and post-processing of DFT output and creating
    tight-binding models for NEGF transport
  license: MPL-2.0

requirements:
  host:
    - numpy
    - pyparsing
  run:
    - pyparsing
    - numpy
    - scipy
    - tqdm
    - xarray
    - pandas
    - matplotlib

build:
  script: |
    export CMAKE_ARGS="-DWITH_FORTRAN=OFF"

extra:
  recipe-maintainers:
    - zerothi
