package:
  name: sympy
  version: 1.14.0
  top-level:
    - isympy
    - sympy
requirements:
  run:
    - mpmath
source:
  sha256: e091cc3e99d2141a0ba2847328f5479b05d94a6635cb96148ccb3f34671bd8f5
  url: https://files.pythonhosted.org/packages/py3/s/sympy/sympy-1.14.0-py3-none-any.whl
about:
  home: https://sympy.org
  PyPI: https://pypi.org/project/sympy
  summary: Computer algebra system (CAS) in Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - oscarbenjamin
