package:
  name: crcmod
  version: "1.7"
  top-level:
    - crcmod
source:
  url: https://files.pythonhosted.org/packages/source/c/crcmod/crcmod-1.7.tar.gz
  sha256: dc7051a0db5f2bd48665a990d3ec1cc305a466a77358ca4492826f41f283601e
about:
  home: http://crcmod.sourceforge.net/
  PyPI: https://pypi.org/project/crcmod
  summary: CRC Generator
  license: MIT
extra:
  recipe-maintainers:
    - whitequark
