package:
  name: rdkit
  version: 2025.9.5
source:
  url: https://github.com/rdkit/rdkit/archive/refs/tags/Release_2025_09_5.tar.gz
  sha256: 1ac784a5f83a7db10aa50be0cd213eba7c1f3436ed4da12363e57589b571db46
requirements:
  host:
    - boost-python
    - matplotlib
    - numpy
    - pandas
  run:
    - matplotlib
    - numpy
    - pandas

build:
  script: |
    export INSTALL_DIR=${WASM_LIBRARY_DIR}
    emcmake cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
    -DCMAKE_BUILD_TYPE=Release \
    -DRDK_INSTALL_INTREE=ON \
    -DRDK_INSTALL_STATIC_LIBS=ON \
    -DRDK_BUILD_CPP_TESTS=ON \
    -DRDK_BUILD_PYTHON_WRAPPERS=ON \
    -DRDK_BUILD_COORDGEN_SUPPORT=ON \
    -DRDK_BUILD_MAEPARSER_SUPPORT=ON \
    -DRDK_OPTIMIZE_POPCNT=ON \
    -DRDK_BUILD_TEST_GZIP=ON \
    -DRDK_BUILD_FREESASA_SUPPORT=ON \
    -DRDK_BUILD_AVALON_SUPPORT=ON \
    -DRDK_BUILD_INCHI_SUPPORT=ON \
    -DRDK_BUILD_YAEHMOP_SUPPORT=ON \
    -DRDK_BUILD_XYZ2MOL_SUPPORT=ON \
    -DRDK_BUILD_CAIRO_SUPPORT=ON \
    -DRDK_BUILD_SWIG_WRAPPERS=OFF \
    -DRDK_SWIG_STATIC=OFF \
    -DRDK_BUILD_THREADSAFE_SSS=ON \
    -DRDK_TEST_MULTITHREADED=ON \
    -DRDK_BUILD_CFFI_LIB=ON \
    -DBoost_INCLUDE_DIR=$WASM_LIBRARY_DIR/include \
    -DBoost_LIBRARY_DIR=$WASM_LIBRARY_DIR/lib \
    -DBoost_NO_SYSTEM_PATHS=ON \
    -DRDK_BOOST_PYTHON3_NAME=python$PYMAJOR.$PYMINOR \
    -DPython3_INCLUDE_DIRS=$PYTHONINCLUDE \
    -DPython3_EXECUTABLE=python$PYMAJOR.$PYMINOR \
    -DPython3_LIBRARY=$HOSTINSTALLDIR/lib/python$PYMAJOR.$PYMINOR.a \
    -DCMAKE_INCLUDE_PATH="$WASM_LIBRARY_DIR/include" \
    -DCMAKE_LIBRARY_PATH="$WASM_LIBRARY_DIR/lib"

    emmake make -j 2
    emmake make -j 2 install

about:
  home: https://github.com/rdkit/rdkit
  PyPI: https://pypi.org/project/rdkit
  summary: A collection of chemoinformatics and machine-learning software written in C++ and Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - fxcoudert
