package:
  name: lxml
  version: 6.0.1
  top-level:
    - lxml
source:
  sha256: 2b3a882ebf27dd026df3801a87cf49ff791336e0f94b0fad195db77e01240690
  url: https://files.pythonhosted.org/packages/source/l/lxml/lxml-6.0.1.tar.gz
build:
  cflags: |
    -Wno-implicit-function-declaration
requirements:
  host:
    - libxml
    - libxslt
    - libzlib
    - libiconv
test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
about:
  home: https://lxml.de/
  PyPI: https://pypi.org/project/lxml
  summary:
    Powerful and Pythonic XML processing library combining libxml2/libxslt
    with the ElementTree API.
  license: BSD-3-Clause
