package:
  name: lxml
  version: 6.0.2
  top-level:
    - lxml
source:
  sha256: cd79f3367bd74b317dda655dc8fcfa304d9eb6e4fb06b7168c5cf27f96e0cd62
  url: https://files.pythonhosted.org/packages/source/l/lxml/lxml-6.0.2.tar.gz
build:
  cflags: |
    -Wno-implicit-function-declaration
requirements:
  host:
    - libxml
    - libxslt
    - libzlib
    - libiconv
test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
about:
  home: https://lxml.de/
  PyPI: https://pypi.org/project/lxml
  summary:
    Powerful and Pythonic XML processing library combining libxml2/libxslt
    with the ElementTree API.
  license: BSD-3-Clause
