package:
  name: lxml
  version: 6.0.0
  top-level:
    - lxml
source:
  sha256: 032e65120339d44cdc3efc326c9f660f5f7205f3a535c1fdbf898b29ea01fb72
  url: https://files.pythonhosted.org/packages/source/l/lxml/lxml-6.0.0.tar.gz
build:
  cflags: |
    -Wno-implicit-function-declaration
requirements:
  host:
    - libxml
    - libxslt
    - libzlib
    - libiconv
test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
about:
  home: https://lxml.de/
  PyPI: https://pypi.org/project/lxml
  summary:
    Powerful and Pythonic XML processing library combining libxml2/libxslt
    with the ElementTree API.
  license: BSD-3-Clause
