package:
  name: propcache
  version: 0.4.1
  top-level:
    - propcache
source:
  url: https://files.pythonhosted.org/packages/py3/p/propcache/propcache-0.4.1-py3-none-any.whl
  sha256: af2a6052aeb6cf17d3e46ee169099044fd8224cbaf75c76a2ef596e8163e2237
about:
  home: https://github.com/aio-libs/propcache
  PyPI: https://pypi.org/project/propcache
  summary: Accelerated property cache
  license: Apache-2.0
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
