package:
  name: coolprop
  version: 7.2.0
  # Now uses upstream scikit-build-core-based build; local pyproject.toml/setup.py no longer needed
  pinned: true
  top-level:
    - CoolProp

source:
  url: https://sourceforge.net/projects/coolprop/files/CoolProp/7.2.0/source/CoolProp_sources.zip
  sha256: 2bd601b5e06b8765ab77fa121e2b0f4087b249c721ddb8745fd3e65952329689
  extract_dir: source


build:
  cflags: -fwasm-exceptions
  cxxflags: -fwasm-exceptions
  ldflags: -fwasm-exceptions

requirements:
  host:
    - python
    - scikit-build-core
    - cmake
    - ninja
  run:
    - numpy
    - matplotlib
  constraint:
    - cython < 3.1.0
test:
  imports:
    - CoolProp
    - CoolProp.GUI
    - CoolProp.Plots

about:
  home: http://www.coolprop.org
  PyPI: https://pypi.org/project/CoolProp
  summary: Open-source thermodynamic and transport properties database
  license: MIT
