package:
  name: tzdata
  version: "2025.3"
  top-level:
    - tzdata
source:
  url: https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl
  sha256: 06a47e5700f3081aab02b2e513160914ff0694bce9947d6b76ebd6bf57cfc5d1
about:
  home: https://github.com/python/tzdata
  PyPI: https://pypi.org/project/tzdata
  summary: Provider of IANA time zone data
  license: Apache-2.0
