package:
  name: autograd
  version: 1.8.0
  top-level:
    - autograd
source:
  sha256: 107374ded5b09fc8643ac925348c0369e7b0e73bbed9565ffd61b8fd04425683
  url: https://files.pythonhosted.org/packages/source/a/autograd/autograd-1.8.0.tar.gz
requirements:
  host:
    - numpy
  run:
    - numpy
    - future
about:
  home: https://github.com/HIPS/autograd
  PyPI: https://pypi.org/project/autograd
  summary: Efficiently computes derivatives of numpy code.
  license: MIT
