package:
  name: altair
  version: 6.0.0
  top-level:
    - altair
source:
  url: https://files.pythonhosted.org/packages/py3/a/altair/altair-6.0.0-py3-none-any.whl
  sha256: 09ae95b53d5fe5b16987dccc785a7af8588f2dca50de1e7a156efa8a461515f8
about:
  home: https://altair-viz.github.io/
  PyPI: https://pypi.org/project/altair
  summary: "Vega-Altair: A declarative statistical visualization library for Python."
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joelostblom
requirements:
  run:
    - typing-extensions
    - Jinja2
    - jsonschema
    - packaging
    - narwhals
    
