package:
  name: logbook
  version: 1.9.2
  top-level:
    - logbook
source:
  url: https://files.pythonhosted.org/packages/source/l/logbook/logbook-1.9.2.tar.gz
  sha256: 0538cabfd8e8a02b8185fb7a2be20b3965d225fbd7f4a5726b007d8e26b39ee0

requirements:
  host:
    - setuptools
  run:
    - typing-extensions
about:
  home: http://logbook.pocoo.org/
  PyPI: https://pypi.org/project/logbook
  summary: A logging replacement for Python
  license: BSD-3-Clause
