package:
  name: taglib
  version: "2.1.1"
  tag:
    - library
    - shared_library
    - cmake
source:
  url: https://github.com/taglib/taglib/releases/download/v2.1.1/taglib-2.1.1.tar.gz
  sha256: 3716d31f7c83cbf17b67c8cf44dd82b2a2f17e6780472287a16823e70305ddba

build:
  type: shared_library
  script: |
    # See https://github.com/supermihi/pytaglib/blob/9e315c2b932d96fa54c2477a82747d0d9f211c87/build_native_taglib.py#L155-L167
    emcmake cmake \
      -DWITH_ZLIB=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DBUILD_TESTING=OFF \
      -DBUILD_EXAMPLES=OFF \
      -DBUILD_SHARED_LIBS=ON \
      ./

    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
    cp ${WASM_LIBRARY_DIR}/lib/libtag.so ${WASM_LIBRARY_DIR}/lib/libtag_c.so ${DISTDIR}

about:
  license: LGPL-2.1 AND MPL-1.1

extra:
  recipe-maintainers:
    - swnf
