package:
  name: pkgconfig
  version: 1.6.0
  top-level:
    - pkgconfig
source:
  url: https://files.pythonhosted.org/packages/py3/p/pkgconfig/pkgconfig-1.6.0-py3-none-any.whl
  sha256: 98e71754855e9563838d952a160eb577edabb57782e49853edb5381927e6bea1
about:
  home: https://github.com/matze/pkgconfig
  PyPI: https://pypi.org/project/pkgconfig
  summary: Interface Python with pkg-config
  license: MIT
