package:
  name: cryptography
  version: 45.0.6
  tag:
    - rust
  top-level:
    - cryptography
source:
  url: https://files.pythonhosted.org/packages/d6/0d/d13399c94234ee8f3df384819dc67e0c5ce215fb751d567a55a1f4b028c7/cryptography-45.0.6.tar.gz
  sha256: 5c966c732cf6e4a276ce83b6e4c729edda2df6929083a952cc7da973c539c719
  patches:
    - patches/0001-Tell-rust-lang-libc-that-time_t-is-64-bits.patch
build:
  script: |
    export OPENSSL_DIR=$WASM_LIBRARY_DIR
requirements:
  run:
    - libopenssl
    - six
    - cffi
  host:
    - libopenssl
    - cffi
  executable:
    - rustup
test:
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.utils
    - cryptography.x509
about:
  home: https://github.com/pyca/cryptography
  PyPI: https://pypi.org/project/cryptography
  summary:
    cryptography is a package which provides cryptographic recipes and primitives
    to Python developers.
  license: BSD-3-Clause OR Apache-2.0
