package:
  name: cryptography
  version: 45.0.4
  tag:
    - rust
  top-level:
    - cryptography
source:
  url: https://files.pythonhosted.org/packages/fe/c8/a2a376a8711c1e11708b9c9972e0c3223f5fc682552c82d8db844393d6ce/cryptography-45.0.4.tar.gz
  sha256: 7405ade85c83c37682c8fe65554759800a4a8c54b2d96e0f8ad114d31b808d57
  patches:
    - patches/0001-Tell-rust-lang-libc-that-time_t-is-64-bits.patch
build:
  script: |
    export OPENSSL_DIR=$WASM_LIBRARY_DIR
requirements:
  run:
    - openssl
    - six
    - cffi
  host:
    - libopenssl
    - cffi
  executable:
    - rustup
test:
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.utils
    - cryptography.x509
about:
  home: https://github.com/pyca/cryptography
  PyPI: https://pypi.org/project/cryptography
  summary:
    cryptography is a package which provides cryptographic recipes and primitives
    to Python developers.
  license: BSD-3-Clause OR Apache-2.0
