package:
  name: cryptography
  version: 46.0.3
  tag:
    - rust
  top-level:
    - cryptography
source:
  url: https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-46.0.3.tar.gz
  sha256: a8b17438104fed022ce745b362294d9ce35b4c2e45c1d958ad4a4b019285f4a1
  patches:
    - patches/0001-Tell-rust-lang-libc-that-time_t-is-64-bits.patch
build:
  vendor-sharedlib: true
  script: |
    export OPENSSL_DIR=$WASM_LIBRARY_DIR
requirements:
  run:
    - six
    - cffi
  host:
    - libopenssl
    - cffi
  executable:
    - rustup
test:
  imports:
    - cryptography
    - cryptography.exceptions
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.utils
    - cryptography.x509
about:
  home: https://github.com/pyca/cryptography
  PyPI: https://pypi.org/project/cryptography
  summary:
    cryptography is a package which provides cryptographic recipes and primitives
    to Python developers.
  license: BSD-3-Clause OR Apache-2.0
