package:
  name: cryptography
  version: 46.0.1
  tag:
    - rust
  top-level:
    - cryptography
source:
  url: https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-46.0.1.tar.gz
  sha256: ed570874e88f213437f5cf758f9ef26cbfc3f336d889b1e592ee11283bb8d1c7
  patches:
    - patches/0001-Tell-rust-lang-libc-that-time_t-is-64-bits.patch
build:
  script: |
    export OPENSSL_DIR=$WASM_LIBRARY_DIR
requirements:
  run:
    - libopenssl
    - six
    - cffi
  host:
    - libopenssl
    - cffi
  executable:
    - rustup
test:
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.utils
    - cryptography.x509
about:
  home: https://github.com/pyca/cryptography
  PyPI: https://pypi.org/project/cryptography
  summary:
    cryptography is a package which provides cryptographic recipes and primitives
    to Python developers.
  license: BSD-3-Clause OR Apache-2.0
