package:
  name: pywavelets
  version: 1.9.0
  top-level:
    - pywt
source:
  sha256: 148d12203377772bea452a59211d98649c8ee4a05eff019a9021853a36babdc8
  url: https://files.pythonhosted.org/packages/source/p/pywavelets/pywavelets-1.9.0.tar.gz
requirements:
  host:
    - numpy
  run:
    - numpy
about:
  home: https://github.com/PyWavelets/pywt
  PyPI: https://pypi.org/project/pywavelets
  summary: PyWavelets, wavelet transform module
  license: MIT
