package:
  name: biopython
  version: "1.87"
  top-level:
    - Bio
    - BioSQL
source:
  sha256: 8456c803459b679a9712422e5a7fd9809f2f089bf69bb085f3b077946ac9bdbf
  url: https://files.pythonhosted.org/packages/source/b/biopython/biopython-1.87.tar.gz
requirements:
  run:
    - numpy
about:
  home: https://biopython.org/
  PyPI: https://pypi.org/project/biopython
  summary: Freely available tools for computational molecular biology.
  license: Biopython
