package:
  name: matplotlib-inline
  version: 0.2.1
requirements:
  run:
    - traitlets
source:
  url: https://files.pythonhosted.org/packages/af/33/ee4519fa02ed11a94aef9559552f3b17bb863f2ecfe1a35dc7f548cde231/matplotlib_inline-0.2.1-py3-none-any.whl
  sha256: d56ce5156ba6085e00a9d54fead6ed29a9c47e215cd1bba2e976ef39f5710a76
about:
  home: https://github.com/ipython/matplotlib-inline
  PyPI: https://pypi.org/project/matplotlib-inline
  summary: Inline Matplotlib backend for Jupyter
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - mhochsteger
