package:
  name: pcodec
  version: 1.0.1
  tag:
    - rust
  top-level:
    - pcodec
source:
  url: https://files.pythonhosted.org/packages/source/p/pcodec/pcodec-1.0.1.tar.gz
  sha256: 559112623ae9ffb42f9f3fdffb5b0cb27d5c363b104994e66a6c0f1093e2de83
requirements:
  executable:
    - rustup
    - cargo
  run:
    - numpy
test:
  imports:
    - pcodec
about:
  home: https://github.com/mwlon/pcodec
  PyPI: https://pypi.org/project/pcodec
  summary: Good compression for numerical sequences
  license: Apache-2.0
