package:
  name: pluggy
  version: 1.6.0
  top-level:
    - pluggy
source:
  sha256: e920276dd6813095e9377c0bc5566d94c932c33b27a3e3945d8389c374dd4746
  url: https://files.pythonhosted.org/packages/py3/p/pluggy/pluggy-1.6.0-py3-none-any.whl
about:
  home: https://github.com/pytest-dev/pluggy
  PyPI: https://pypi.org/project/pluggy
  summary: plugin and hook calling mechanisms for python
  license: MIT
