package:
  name: primecountpy
  version: 0.2.1
  top-level:
    - primecountpy
source:
  # Cannot use tar.gz from PyPI becuase of https://github.com/dimpase/primecountpy/issues/20
  url: https://files.pythonhosted.org/packages/source/p/primecountpy/primecountpy-0.2.1.tar.gz
  sha256: 888706ab65cc089fb983de4639360dddc728baa4d9877a7ad8b116f645650b39
about:
  home: https://github.com/dimpase/primecountpy
  PyPI: https://pypi.org/project/primecountpy
  summary: Cython interface for C++ primecount library
  license: GPL-3.0
requirements:
  host:
    - libprimecount
    - libprimesieve
  run:
    - cysignals
build:
  cxxflags: |
    -std=c++17
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
extra:
  recipe-maintainers:
    - mkoeppe
