package:
  name: primecountpy
  version: 0.1.1
  top-level:
    - primecountpy
source:
  # Cannot use tar.gz from PyPI becuase of https://github.com/dimpase/primecountpy/issues/20
  url: https://github.com/dimpase/primecountpy/releases/download/v0.1.1/primecountpy-0.1.1.tar.gz
  sha256: bed77c4d519092ae4489a3a8dfc2ab68e18aeec6c88dea5bb5fac6cffc0f5b20
about:
  home: https://github.com/dimpase/primecountpy
  PyPI: https://pypi.org/project/primecountpy
  summary: Cython interface for C++ primecount library
  license: GPL-3.0
requirements:
  host:
    - libprimecount
    - primesieve
  run:
    - cysignals
build:
  cxxflags: |
    -std=c++17
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
extra:
  recipe-maintainers:
    - mkoeppe
