package:
  name: scs
  version: 3.2.11
  top-level:
    - scs
source:
  url: https://files.pythonhosted.org/packages/source/s/scs/scs-3.2.11.tar.gz
  sha256: 2a5455cf2093d07f84f2f848c199faed52e79cdb3a11fe250b5622b6bbac4913
about:
  home: https://github.com/cvxgrp/scs
  PyPI: https://pypi.org/project/scs
  summary: SCS (splitting conic solver) is a numerical optimization package for
    solving large-scale convex cone problems.
  license: MIT
requirements:
  run:
    - numpy
    - scipy
extra:
  recipe-maintainers:
    - langestefan
    - PTNobel
