package:
  name: beautifulsoup4
  version: 4.14.3
  top-level:
    - bs4
requirements:
  run:
    - soupsieve
    - typing-extensions
source:
  sha256: 0918bfe44902e6ad8d57732ba310582e98da931428d231a5ecb9e7c703a735bb
  url: https://files.pythonhosted.org/packages/py3/b/beautifulsoup4/beautifulsoup4-4.14.3-py3-none-any.whl
about:
  home: https://www.crummy.com/software/BeautifulSoup/bs4/
  PyPI: https://pypi.org/project/beautifulsoup4
  summary: Screen-scraping library
  license: MIT
