package:
  name: pi-heif
  version: 1.3.0
  top-level:
    - pi_heif
source:
  url: https://files.pythonhosted.org/packages/source/p/pi_heif/pi_heif-1.3.0.tar.gz
  sha256: 58151840d0d60507330654a466b06cbf7ca8fb3759eadb5234d70b4dc2bc990c
requirements:
  run:
    - cffi
    - Pillow
  host:
    - cffi
    - libheif
build:
  vendor-sharedlib: true
  script: |
    export LIBHEIF_ROOT=${WASM_LIBRARY_DIR}
test:
  imports:
    - pi_heif
about:
  home: https://github.com/bigcat88/pillow_heif
  PyPI: https://pypi.org/project/pi_heif
  summary: Python 3.6+ interface to libheif library
  license: LGPL-2.1
extra:
  recipe-maintainers:
    - airen1986
