package:
  name: bcrypt
  version: 5.0.0
  tag:
    - rust
  top-level:
    - bcrypt
source:
  url: https://files.pythonhosted.org/packages/source/b/bcrypt/bcrypt-5.0.0.tar.gz
  sha256: f748f7c2d6fd375cc93d3fba7ef4a9e3a092421b8dbf34d8d4dc06be9492dfdd
requirements:
  executable:
    - rustup
about:
  home: https://github.com/pyca/bcrypt/
  PyPI: https://pypi.org/project/bcrypt
  summary: Modern password hashing for your software and your servers
  license: Apache-2.0
