name: pyodide-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nodejs
  - ccache
  - f2c
  - swig
  - make
  - cmake
  - texinfo
  - autoconf
  - automake
  - libtool
  - wget
  - setuptools
  - gfortran
  - pip:
    - pytest
    - pytest-pyodide==0.53.1
    - pytest-httpserver
