name: pyodide-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - nodejs=20
  - ccache
  - f2c
  - swig
  - make
  - cmake
  - texinfo
  - autoconf
  - automake
  - libtool
  - wget
  - setuptools
  - gfortran
  - pip:
    - pytest
    - pytest-pyodide==0.56.2
    - pytest-httpserver
