name: pyodide-env
channels:
  - conda-forge
dependencies:
  - python=3.13.0
  - nodejs=20
  - ccache
  - f2c
  - swig
  - make
  - cmake<4
  - texinfo
  - autoconf
  - automake
  - libtool
  - wget
  - setuptools
  - gfortran
