package:
  name: pytest-asyncio
  version: 1.3.0
  tag:
    - core
    - min-scipy-stack
  top-level:
    - pytest_asyncio
source:
  url: https://files.pythonhosted.org/packages/py3/p/pytest_asyncio/pytest_asyncio-1.3.0-py3-none-any.whl
  sha256: 611e26147c7f77640e6d0a92a38ed17c3e9848063698d5c93d5aa7aa11cebff5
requirements:
  run:
    - pytest
about:
  home: https://github.com/pytest-dev/pytest-asyncio
  PyPI: https://pypi.org/project/pytest-asyncio
  summary: Pytest support for asyncio
  license: Apache-2.0
extra:
  recipe-maintainers:
    - agriyakhetarpal
