package:
  name: imgui-bundle
  version: 1.92.600
  top-level:
    - imgui_bundle
source:
  url: https://github.com/pthom/imgui_bundle/releases/download/v1.92.600/imgui_bundle-1.92.600-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: fb25175086432040f7f42199b9d6b3679016c610156d4fd80af1cc5898cdc7a4
requirements:
  run:
    - pydantic
    - munch
    - numpy
extra:
  recipe-maintainers:
    - pthom
about:
  home: http://pthom.github.io/imgui_bundle/
  PyPI: https://pypi.org/project/imgui-bundle/
  summary: "Dear ImGui Bundle: From expressive code to powerful GUIs in no time. A fast, feature-rich, cross-platform toolkit for C++ and Python."
  license: MIT
