package:
  name: imgui-bundle
  version: 1.92.601
  _disabled: true  # update to 2026_0
  top-level:
    - imgui_bundle
source:
  url: https://github.com/pthom/imgui_bundle/releases/download/v1.92.601/imgui_bundle-1.92.601-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: 6df918f3af424ceab037cd8f69c7e79d7d27eda5af11870ffa29cb7e01fac23b
requirements:
  run:
    - pydantic
    - munch
    - numpy
extra:
  recipe-maintainers:
    - pthom
about:
  home: http://pthom.github.io/imgui_bundle/
  PyPI: https://pypi.org/project/imgui-bundle/
  summary: "Dear ImGui Bundle: From expressive code to powerful GUIs in no time. A fast, feature-rich, cross-platform toolkit for C++ and Python."
  license: MIT
