package:
  name: imgui-bundle
  version: 1.92.0
  top-level:
    - imgui_bundle

source:
  url: https://github.com/pthom/imgui_bundle/releases/download/v1.92.0/srcs-full-v1.92.0.tar.gz
  sha256: 359336ca8edeef3e1313652be86d4a3aacb28962f4906926ca0db3817c27fcdb

build:
  # imgui-bundle needs to link with relocatable versions of SDL2 and html5.
  # By default, emscripten builds the non-relocatable version of these libraries,
  # so we need to trigger the build of the relocatable (-fPIC) versions.
  # See https://github.com/pyodide/pyodide/issues/5248 for more explanations.
  script: |
    embuilder build sdl2 libhtml5 --pic

requirements:
  run:
    - pydantic
    - munch
    - numpy

extra:
  recipe-maintainers:
    - pthom
