package:
  name: lakers-python
  version: 0.6.0
  tag:
    - rust
  top-level:
    - lakers
source:
  url: https://files.pythonhosted.org/packages/2a/e6/416be35d38c50af5475fa55324ef16f9e6f5039a750974f54da78f8fd3e6/lakers_python-0.6.0.tar.gz
  sha256: fac63f3f5679a04d9277311c1f3e8eacee02a10e456547187f1a9695b6b3a333
requirements:
  executable:
    - rustup
about:
  home: https://github.com/openwsn-berkeley/lakers/
  PyPI: https://pypi.org/project/lakers-python/
  summary: An implementation of EDHOC (RFC 9528)
  license: BSD-3-Clause
