package:
  name: lakers-python
  version: 0.6.2
  tag:
    - rust
  top-level:
    - lakers
source:
  url: https://files.pythonhosted.org/packages/8c/09/942939302f2e2473f4f601a90c53426db5dac4a9ae22f5bf9340a9fe3fb7/lakers_python-0.6.2.tar.gz
  sha256: bc4dbe014161e4023a95affa93b9f3648f218acb6b1d99a5bc98dd7f676c5d56
requirements:
  executable:
    - rustup
about:
  home: https://github.com/openwsn-berkeley/lakers/
  PyPI: https://pypi.org/project/lakers-python/
  summary: An implementation of EDHOC (RFC 9528)
  license: BSD-3-Clause
