package:
  name: libcrc32c
  version: 1.1.0

source:
  url: https://github.com/google/crc32c/archive/refs/tags/1.1.1.tar.gz
  sha256: a6533f45b1670b5d59b38a514d82b09c6fb70cc1050467220216335e873074e8

build:
  type: shared_library
  script: |
    mkdir -p build;

    cd build \
        && emcmake cmake ../ \
        -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
        -DBUILD_SHARED_LIBS=ON \
        -DCRC32C_BUILD_TESTS=OFF \
        -DCRC32C_BUILD_BENCHMARKS=OFF \
        -DCRC32C_USE_GLOG=OFF;

    emmake make -j ${PYODIDE_JOBS:-3};
    emmake make -j ${PYODIDE_JOBS:-3} install;

    cp -P ${WASM_LIBRARY_DIR}/lib/libcrc32c.so ${DISTDIR}
