package:
  name: galpy
  version: 1.11.2
  top-level:
    - galpy
source:
  url: https://files.pythonhosted.org/packages/source/g/galpy/galpy-1.11.2.tar.gz
  sha256: 5180a25743e6c8e5fbaffc1ff89f22940276b6341b2d3a9c4ca5e348eb071e5e
build:
  script: export LIBGSL_INCLUDE_PATH=$(pkg-config --cflags-only-I
    --dont-define-prefix gsl) export LIBGSL_LIBRARY_PATH=$(pkg-config
    --libs-only-L --dont-define-prefix gsl)
  cflags: |
    $(LIBGSL_INCLUDE_PATH)
  ldflags: |
    $(LIBGSL_LIBRARY_PATH)
  exports: requested
requirements:
  run:
    - numpy
    - scipy
    - matplotlib
    - astropy
    - future
    - setuptools
  host:
    - libgsl
    - numpy
    - scipy
test:
  imports:
    - galpy
    - galpy.potential
    - galpy.orbit
    - galpy.actionAngle
    - galpy.df
about:
  home: http://github.com/jobovy/galpy
  PyPI: https://pypi.org/project/galpy
  summary: Galactic Dynamics in python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - jobovy
