package:
  name: vrplib
  version: 2.0.1
  top-level:
    - vrplib
source:
  url: https://files.pythonhosted.org/packages/26/54/ef1aa5b1e388a42480d181cae0d1477f99cad1f1590312c74ce2853cf9e8/vrplib-2.0.1-py3-none-any.whl
  sha256: 1c4d9693cd0ef8d904e18f890a5647b2dd8e726e13e784a3f5e16ddda2515d53
requirements:
  run:
    - numpy
about:
  home: https://github.com/PyVRP/VRPLIB
  PyPI: https://pypi.org/project/vrplib
  summary: Python library for reading and writing VRP instances.
  license: null
extra:
  recipe-maintainers:
    - airen1986
