package:
  name: newick
  version: 1.11.0
  top-level:
    - newick
source:
  url: https://files.pythonhosted.org/packages/py2.py3/n/newick/newick-1.11.0-py2.py3-none-any.whl
  sha256: c431976e33ea9166d6bf87394408086ce616930a5a434a30883220dee547d6eb
about:
  home: https://github.com/dlce-eva/python-newick
  PyPI: https://pypi.org/project/newick
  summary: A python module to read and write the Newick format
  license: Apache-2.0
