package:
  name: yarl
  version: 1.23.0
  top-level:
    - yarl
source:
  url: https://files.pythonhosted.org/packages/source/y/yarl/yarl-1.23.0.tar.gz
  sha256: 53b1ea6ca88ebd4420379c330aea57e258408dd0df9af0992e5de2078dc9f5d5
requirements:
  run:
    - multidict
    - idna
    - propcache
about:
  home: https://github.com/aio-libs/yarl/
  PyPI: https://pypi.org/project/yarl
  summary: Yet another URL library
  license: Apache-2.0
