package:
  name: bitarray
  version: 3.6.1
  top-level:
    - bitarray
source:
  url: https://files.pythonhosted.org/packages/source/b/bitarray/bitarray-3.6.1.tar.gz
  sha256: 4255bff37b01562b8e6adcf9db256029765985b0790c5ff76bbe1837edcd53ea
about:
  home: https://github.com/ilanschnell/bitarray
  PyPI: https://pypi.org/project/bitarray
  summary: efficient arrays of booleans -- C extension
  license: PSF-2.0
