package:
  name: bitarray
  version: 3.8.1
  top-level:
    - bitarray
source:
  url: https://files.pythonhosted.org/packages/source/b/bitarray/bitarray-3.8.1.tar.gz
  sha256: f90bb3c680804ec9630bcf8c0965e54b4de84d33b17d7da57c87c30f0c64c6f5
about:
  home: https://github.com/ilanschnell/bitarray
  PyPI: https://pypi.org/project/bitarray
  summary: efficient arrays of booleans -- C extension
  license: PSF-2.0
