package:
  name: bitarray
  version: 3.4.3
  top-level:
    - bitarray
source:
  url: https://files.pythonhosted.org/packages/source/b/bitarray/bitarray-3.4.3.tar.gz
  sha256: dddfb2bf086b66aec1c0110dc46642b7161f587a6441cfe74da9e323975f62f0
about:
  home: https://github.com/ilanschnell/bitarray
  PyPI: https://pypi.org/project/bitarray
  summary: efficient arrays of booleans -- C extension
  license: PSF-2.0
