package:
  name: bitarray
  version: 3.7.0
  top-level:
    - bitarray
source:
  url: https://files.pythonhosted.org/packages/source/b/bitarray/bitarray-3.7.0.tar.gz
  sha256: ae8fb4107c7a43f8979875dc465cab605b75b108e0db7a92da1a727128d0c865
about:
  home: https://github.com/ilanschnell/bitarray
  PyPI: https://pypi.org/project/bitarray
  summary: efficient arrays of booleans -- C extension
  license: PSF-2.0
