package:
  name: bitarray
  version: 3.7.2
  top-level:
    - bitarray
source:
  url: https://files.pythonhosted.org/packages/source/b/bitarray/bitarray-3.7.2.tar.gz
  sha256: 27a59bb7c64c0d094057a3536e15fdd693f8520771ee75d9344b82d0a5ade2d0
about:
  home: https://github.com/ilanschnell/bitarray
  PyPI: https://pypi.org/project/bitarray
  summary: efficient arrays of booleans -- C extension
  license: PSF-2.0
