package:
  name: setuptools
  version: 82.0.1
  top-level:
    - _distutils_hack
    - setuptools
source:
  url: https://files.pythonhosted.org/packages/py3/s/setuptools/setuptools-82.0.1-py3-none-any.whl
  sha256: a59e362652f08dcd477c78bb6e7bd9d80a7995bc73ce773050228a348ce2e5bb
build:
  post: |
    find . -name '*.exe' -delete
requirements:
  run:
    - pyparsing
about:
  home: https://github.com/pypa/setuptools
  PyPI: https://pypi.org/project/setuptools
  summary: Easily download, build, install, upgrade, and uninstall Python
    packages
  license: MIT
