package:
  name: tblib
  version: 3.2.2
  top-level:
    - tblib
  tag:
    - always
    - core
    - min-scipy-stack
source:
  url: https://files.pythonhosted.org/packages/py3/t/tblib/tblib-3.2.2-py3-none-any.whl
  sha256: 26bdccf339bcce6a88b2b5432c988b266ebbe63a4e593f6b578b1d2e723d2b76
about:
  home: https://github.com/ionelmc/python-tblib
  PyPI: https://pypi.org/project/tblib
  summary: Traceback serialization library.
  license: BSD-2-Clause
