package:
  name: blosc2
  version: 3.5.1
  top-level:
    - blosc2
source:
  url: https://files.pythonhosted.org/packages/source/b/blosc2/blosc2-3.5.1.tar.gz
  sha256: 5d72f7a9a8b3b523c588be9d66e9e7f2463483716c4c01e5056c1f7e37167f85
build:
  backend-flags: |
    skbuild.cmake.define.WITH_OPTIM=OFF

requirements:
  host:
    # Dependencies that are needed to build the package
    - numpy
  run:
    # Dependencies that are needed to run the package
    - numpy
    - msgpack
    - requests
    - ndindex
    - platformdirs

about:
  home: https://github.com/Blosc/python-blosc2
  PyPI: https://pypi.org/project/blosc2
  summary: A fast & compressed ndarray library with a flexible compute engine.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - FrancescAlted
