package:
  name: blosc2
  version: 4.1.2
  top-level:
    - blosc2
source:
  url: https://files.pythonhosted.org/packages/source/b/blosc2/blosc2-4.1.2.tar.gz
  sha256: c127342d976de44fee242137e83660097e0b072779f4164a34e149ac9f693c8a
build:
  backend-flags: |
    skbuild.cmake.define.WITH_OPTIM=OFF

requirements:
  host:
    # Dependencies that are needed to build the package
    - numpy
  run:
    # Dependencies that are needed to run the package
    - numpy
    - msgpack
    - requests
    - ndindex
    - platformdirs

about:
  home: https://github.com/Blosc/python-blosc2
  PyPI: https://pypi.org/project/blosc2
  summary: A fast & compressed ndarray library with a flexible compute engine.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - FrancescAlted
