package:
  name: scipy
  version: 1.16.0
  tag:
    - min-scipy-stack
  top-level:
    - scipy

# See extra explanation in info.md
#
# For future reference: if you see the following errors:
#   Declaration error: adjustable dimension on non-argument
# or:
#   nonconstant array size
# you are trying to compile code that isn't written to the fortran 77 standard.
# The line number in the error points to the last line of the problematic
# subroutine. Try deleting it.

source:
  url: https://files.pythonhosted.org/packages/source/s/scipy/scipy-1.16.0.tar.gz
  sha256: b5ef54021e832869c8cfb03bc3bf20366cbcd426e02a58e8a58d7584dfbb8f62

  patches:
    - patches/0001-Fix-dstevr-in-special-lapack_defs.h.patch
    - patches/0002-int-to-string.patch
    - patches/0003-gemm_-no-const.patch
    - patches/0004-make-int-return-values.patch
    - patches/0005-Fix-fitpack.patch
    - patches/0006-Fix-gees-calls.patch
    - patches/0007-Make-sreorth-recursive.patch
    - patches/0008-Link-openblas-with-modules-that-require-f2c.patch
    - patches/0009-Remove-chla_transtype.patch
    - patches/0010-Set-wrapper-return-type-to-int.patch
    - patches/0011-Remove-test-modules-that-fail-to-build.patch
    - patches/0012-Fix-lapack-larfg-function-signature.patch
    - patches/0013-ENH-MAINT-sparse.linalg-rewrite-ARPACK-in-C-22748.patch
    - patches/0014-Remove-f2py-generators.patch

build:
  # NumPy 2.1 disabled visibility for symbols outside of extension modules
  # by default, so this breaks SciPy tests from modules that use f2py to
  # build because they rely on the visibility of symbols in NumPy. This flag
  # is currently used as a stop-gap measure. For more information, please see
  # 1. https://github.com/numpy/numpy/pull/26286, and
  # 2. https://github.com/numpy/numpy/pull/26103.
  cflags: |
    -DNPY_API_SYMBOL_ATTRIBUTE=__attribute__((visibility("default")))
    -I$(WASM_LIBRARY_DIR)/include
    -Wno-return-type
    -DUNDERSCORE_G77
    -fvisibility=default
  cxxflags: |
    -fwasm-exceptions
    -fvisibility=default
  ldflags: |
    -L$(NUMPY_LIB)/core/lib/
    -L$(NUMPY_LIB)/random/lib/
    -fwasm-exceptions

  # Exclude tests via Meson's install tags functionality.
  unvendor-tests: true
  # install-args=--tags=runtime,python-runtime,devel
  # Disable when running tests, enable when a PR is ready, i.e., building for distribution.
  backend-flags: |
    build-dir=build

  # IMPORTANT: Other locations important in scipy build process:
  # There are two files built in the "capture" pass that need patching:
  #    _blas_subroutines.h, and _cython
  # Scipy has a bunch of custom logic implemented in
  # pyodide-build/pyodide_build/_f2c_fixes.py.
  script: |
    set -x
    git clone https://github.com/hoodmane/f2c.git --depth 1
    (cd f2c/src && cp makefile.u makefile && sed -i "s/gram.c:/gram.c1:/" makefile && make)
    export F2C_PATH=$(pwd)/f2c/src/f2c

    echo F2C_PATH: $F2C_PATH
    export NPY_BLAS_LIBS="-I$WASM_LIBRARY_DIR/include $WASM_LIBRARY_DIR/lib/libopenblas.so"
    export NPY_LAPACK_LIBS="-I$WASM_LIBRARY_DIR/include $WASM_LIBRARY_DIR/lib/libopenblas.so"

    sed -i 's/void DQA/int DQA/g' scipy/integrate/__quadpack.h

    # Change many functions that return void into functions that return int
    find scipy -name "*.c*" -type f | xargs sed -i 's/extern void F_FUNC/extern int F_FUNC/g'

    sed -i 's/void F_FUNC/int F_FUNC/g' scipy/odr/__odrpack.c
    sed -i 's/^void/int/g' scipy/odr/odrpack.h
    sed -i 's/^void/int/g' scipy/odr/__odrpack.c

    sed -i 's/void BLAS_FUNC/int BLAS_FUNC/g' scipy/special/lapack_defs.h
    # sed -i 's/void F_FUNC/int F_FUNC/g' scipy/linalg/_lapack_subroutines.h
    sed -i 's/extern void/extern int/g' scipy/optimize/__minpack.h
    sed -i 's/void/int/g' scipy/linalg/cython_blas_signatures.txt
    sed -i 's/void/int/g' scipy/linalg/cython_lapack_signatures.txt
    sed -i 's/^void/int/g' scipy/linalg/_common_array_utils.h

    sed -i 's/^void/int/g' scipy/interpolate/src/_fitpackmodule.c
    sed -i 's/^void/int/g' scipy/interpolate/src/__fitpack.h
    sed -i 's/^void/int/g' scipy/interpolate/src/__fitpack.cc
    sed -i 's/void BLAS_FUNC/int BLAS_FUNC/g' scipy/interpolate/src/__fitpack.h

    sed -i 's/extern void/extern int/g' scipy/sparse/linalg/_dsolve/SuperLU/SRC/*.{c,h}
    sed -i 's/PUBLIC void/PUBLIC int/g' scipy/sparse/linalg/_dsolve/SuperLU/SRC/*.{c,h}
    sed -i 's/^void/int/g' scipy/sparse/linalg/_dsolve/SuperLU/SRC/*.{c,h}
    sed -i 's/^void/int/g' scipy/sparse/linalg/_dsolve/*.{c,h}
    sed -i 's/void \(.\)print/int \1/g' scipy/sparse/linalg/_dsolve/SuperLU/SRC/*.{c,h}
    sed -i 's/TYPE_GENERIC_FUNC(\(.*\), void)/TYPE_GENERIC_FUNC(\1, int)/g' scipy/sparse/linalg/_dsolve/_superluobject.h

    sed -i 's/^void/int/g' scipy/optimize/__nnls.h
    sed -i 's/^void/int/g' scipy/optimize/__nnls.c
    sed -i 's/^void/int/g' scipy/optimize/__slsqp.h
    sed -i 's/^void/int/g' scipy/optimize/__slsqp.c
    sed -i 's/^static void/static int/g' scipy/optimize/__slsqp.c

    sed -i 's/^void/int/g' scipy/optimize/_trlib/trlib_private.h
    sed -i 's/^void/int/g' scipy/optimize/_trlib/trlib/trlib_private.h
    sed -i 's/^void/int/g' scipy/_build_utils/src/wrap_dummy_g77_abi.c
    sed -i 's/, int)/)/g' scipy/optimize/_trlib/trlib_private.h
    sed -i 's/, 1)/)/g' scipy/optimize/_trlib/trlib_private.h

    sed -i 's/^void/int/g' scipy/linalg/_matfuncs_expm.h
    sed -i 's/^void/int/g' scipy/linalg/_matfuncs_expm.c
    sed -i 's/^void/int/g' scipy/linalg/_matfuncs_sqrtm.h
    sed -i 's/^void/int/g' scipy/linalg/_matfuncs_sqrtm.c

    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double_complex.h
    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_double.h
    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_single_complex.h
    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_n_single.h
    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_s_double.h
    sed -i 's/^void/int/g' scipy/sparse/linalg/_eigen/arpack/ARPACK/_arpack_s_single.h

    sed -i 's/^void/int/g' scipy/spatial/qhull_misc.h
    sed -i 's/, size_t)/)/g' scipy/spatial/qhull_misc.h
    sed -i 's/,1)/)/g' scipy/spatial/qhull_misc.h

    sed -i 's/^void/int/g' scipy/optimize/__lbfgsb.h

    # Input error causes "duplicate symbol" linker errors. Empty out the file.
    echo "" > scipy/sparse/linalg/_dsolve/SuperLU/SRC/input_error.c

    # https://github.com/mesonbuild/meson/blob/e542901af6e30865715d3c3c18f703910a096ec0/mesonbuild/backend/ninjabackend.py#L94
    # Prevent from using response file. The response file that meson generates is not compatible to pyodide-build
    export MESON_RSP_THRESHOLD=131072

  _retain-test-patterns:
    - "*_page_trend_test.py"
    - "*bws_test.py"

  cross-build-env: true
  cross-build-files:
    - scipy/linalg/cython_lapack.pxd
    - scipy/linalg/cython_blas.pxd

requirements:
  host:
    - numpy
    - libopenblas
    - libboost
  run:
    - numpy
    - libopenblas
  executable:
    - gfortran

test:
  imports:
    - scipy
    - scipy.cluster
    - scipy.cluster.vq
    - scipy.cluster.hierarchy
    - scipy.constants
    - scipy.fft
    - scipy.fftpack
    - scipy.integrate
    - scipy.interpolate
    - scipy.io
    - scipy.io.arff
    - scipy.io.matlab
    - scipy.io.wavfile
    - scipy.linalg
    - scipy.linalg.blas
    - scipy.linalg.cython_blas
    - scipy.linalg.lapack
    - scipy.linalg.cython_lapack
    - scipy.linalg.interpolative
    - scipy.misc
    - scipy.ndimage
    - scipy.odr
    - scipy.optimize
    - scipy.signal
    - scipy.signal.windows
    - scipy.sparse
    - scipy.sparse.linalg
    - scipy.sparse.csgraph
    - scipy.spatial
    - scipy.spatial.distance
    - scipy.spatial.transform
    - scipy.special
    - scipy.stats
    - scipy.stats.contingency
    - scipy.stats.distributions
    - scipy.stats.mstats
    - scipy.stats.qmc
about:
  home: https://www.scipy.org
  PyPI: https://pypi.org/project/scipy
  summary: "SciPy: Scientific Library for Python"
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - lesteve
    - steppi
    - agriyakhetarpal
