package:
  name: geopandas
  version: 1.1.1
  top-level:
    - geopandas
source:
  url: https://files.pythonhosted.org/packages/0b/70/d5cd0696eff08e62fdbdebe5b46527facb4e7220eabe0ac6225efab50168/geopandas-1.1.1-py3-none-any.whl
  sha256: 589e61aaf39b19828843df16cb90234e72897e2579be236f10eee0d052ad98e8
requirements:
  run:
    - shapely
    - fiona
    - pyproj
    - packaging
    - pandas
      # - matplotlib # matplotlib is not a hard dependency
about:
  home: http://geopandas.org
  PyPI: https://pypi.org/project/geopandas
  summary: Geographic pandas extensions
  license: BSD-3-Clause
