package:
  name: geopandas
  version: 1.1.1
  top-level:
    - geopandas
source:
  url: https://files.pythonhosted.org/packages/8c/76/e1960ba846f153ab109575242abf89dc98f8e057faa32f3decf4cce9247a/geopandas-1.1.1.tar.gz
  sha256: 1745713f64d095c43e72e08e753dbd271678254b24f2e01db8cdb8debe1d293d
requirements:
  run:
    - shapely
    - fiona
    - pyproj
    - packaging
    - pandas
      # - matplotlib # matplotlib is not a hard dependency
about:
  home: http://geopandas.org
  PyPI: https://pypi.org/project/geopandas
  summary: Geographic pandas extensions
  license: BSD-3-Clause
