package:
  name: pycryptodome
  version: 3.23.0
  top-level:
    - Crypto
source:
  url: https://files.pythonhosted.org/packages/source/p/pycryptodome/pycryptodome-3.23.0.tar.gz
  sha256: 447700a657182d60338bab09fdb27518f8856aecd80ae4c6bdddb67ff5da44ef
build:
  exports: requested
about:
  home: https://www.pycryptodome.org
  PyPI: https://pypi.org/project/pycryptodome
  summary: Cryptographic library for Python
  license: Mixed BSD-2-Clause, Public Domain
