package:
  name: fastuuid
  version: 0.14.0
  top-level:
    - fastuuid
source:
  url: https://files.pythonhosted.org/packages/source/f/fastuuid/fastuuid-0.14.0.tar.gz
  sha256: 178947fc2f995b38497a74172adee64fdeb8b7ec18f2a5934d037641ba265d26
about:
  home: null
  PyPI: https://pypi.org/project/fastuuid
  summary: Python bindings to Rust's UUID library.
  license: null
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
