package:
  name: xlrd
  version: 2.0.2
  top-level:
    - xlrd
source:
  sha256: ea762c3d29f4cca48d82df517b6d89fbce4db3107f9d78713e48cd321d5c9aa9
  url: https://files.pythonhosted.org/packages/py2.py3/x/xlrd/xlrd-2.0.2-py2.py3-none-any.whl
about:
  home: http://www.python-excel.org/
  PyPI: https://pypi.org/project/xlrd
  summary: Library for developers to extract data from Microsoft Excel (tm) .xls
    spreadsheet files
  license: BSD-3-Clause
