package:
  name: PyMuPDF
  version: 1.27.2.2
  top-level:
    - pymupdf
    - fitz
source:
  url: https://files.pythonhosted.org/packages/source/p/pymupdf/pymupdf-1.27.2.2.tar.gz
  sha256: ea8fdc3ab6671ca98f629d5ec3032d662c8cf1796b146996b7ad306ac7ed3335
build:
  vendor-sharedlib: false # done by the package itself
  exports: whole_archive
  ldflags: |
    -Wl,-rpath,$ORIGIN/../PyMuPDF.libs
  script: |
    export PYMUPDF_SETUP_FLAVOUR=pb
    export PYMUPDF_SETUP_MUPDF_TESSERACT=0
    export HAVE_LIBCRYPTO=no
about:
  home: https://pymupdf.readthedocs.io
  PyPI: https://pypi.org/project/pymupdf
  summary: A high performance Python library for data extraction, analysis,
    conversion & manipulation of PDF (and other) documents.
  license: Dual Licensed - GNU AFFERO GPL 3.0 or Artifex Commercial License
extra:
  recipe-maintainers:
    - sanzoghenzo
    - linuxrider
