package:
  name: unyt
  version: 3.1.0
  top-level:
    - unyt
source:
  url: https://files.pythonhosted.org/packages/py3/u/unyt/unyt-3.1.0-py3-none-any.whl
  sha256: 6ff9efe694a1c13f5b07ccb4c6b30a0e282d5e4989947f0ef5aadf4ad7be3f69
requirements:
  run:
    - numpy
    - packaging
    - sympy
about:
  home: https://github.com/yt-project/unyt
  PyPI: https://pypi.org/project/unyt
  summary: A package for handling numpy arrays with units
  license: BSD-3-Clause
