package:
  name: tskit
  version: 1.0.2
  top-level:
    - tskit
source:
  url: https://files.pythonhosted.org/packages/source/t/tskit/tskit-1.0.2.tar.gz
  sha256: 8713108574f278edc42858e586bd7c131f288689f6283586fdb23f990691dcb3
requirements:
  run:
    - numpy
    - jsonschema
    - rpds-py
  host:
    - numpy
about:
  home: https://tskit.dev/tskit
  PyPI: https://pypi.org/project/tskit
  summary: The tree sequence toolkit.
  license: MIT
