package:
  name: tskit
  version: 1.0.0
  top-level:
    - tskit
source:
  url: https://files.pythonhosted.org/packages/17/9d/ffadbb3a411fd2feca7573659d5a6f81c30e4976c497c91a5ac63c1d3065/tskit-1.0.0.tar.gz
  sha256: 77a5f33923d58758ec460d40e3d68c585c9654ddbd9da6326155ecf36290d0e0
requirements:
  run:
    - numpy
    - jsonschema
    - rpds-py
  host:
    - numpy
about:
  home: https://tskit.dev/tskit
  PyPI: https://pypi.org/project/tskit
  summary: The tree sequence toolkit.
  license: MIT
