package:
  name: tskit
  version: 0.6.4
  top-level:
    - tskit
source:
  url: https://files.pythonhosted.org/packages/94/95/2c2d8bdaae4a3948181de68d1fac0569d9c937a42f7ccfcf097f9a428721/tskit-0.6.4.tar.gz
  sha256: bdac1bb7e3ae3d1f562ec191b5d840156e082dd2adc6af7c41b170c4fb1be792
requirements:
  run:
    - numpy
    - jsonschema
    - rpds-py
  host:
    - numpy
about:
  home: https://tskit.dev/tskit
  PyPI: https://pypi.org/project/tskit
  summary: The tree sequence toolkit.
  license: MIT
