package:
  name: python-flint
  version: 0.7.1
  top-level:
    - flint
requirements:
  host:
    - libflint
    - libgmp
    - libmpfr
source:
  url: https://files.pythonhosted.org/packages/source/p/python_flint/python_flint-0.7.1.tar.gz
  sha256: 8594cdbcba0c29503eefca76dfca37fe2388f11ee95c8d1f74e47006b97ce6d2
build:
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib -lflint -lmpfr -lgmp
  unvendor-tests: false
about:
  home: https://github.com/flintlib/python-flint
  PyPI: https://pypi.org/project/python-flint
  summary: Bindings for FLINT and Arb
  license: MIT
extra:
  recipe-maintainers:
    - mkoeppe
    - oscarbenjamin
