package:
  name: fiona
  version: 1.10.1
source:
  url: https://files.pythonhosted.org/packages/source/f/fiona/fiona-1.10.1.tar.gz
  sha256: b00ae357669460c6491caba29c2022ff0acfcbde86a95361ea8ff5cd14a86b68
test:
  imports:
    - fiona
    - fiona.fio
requirements:
  host:
    - libgdal
    - libgeos
  run:
    - attrs
    - certifi
    - setuptools
    - six
    - click
    - cligj
      # - click-plugins  # only for fiona CLI?

build:
  vendor-sharedlib: true
  script: |
    export PACKAGE_DATA=1
    export GDAL_CONFIG=${WASM_LIBRARY_DIR}/bin/gdal-config
    export GDAL_DATA=${WASM_LIBRARY_DIR}/share/gdal
    export PROJ_LIB=${WASM_LIBRARY_DIR}/share/proj
    echo ${GDAL_CONFIG}
    echo ${GDAL_DATA}
    echo ${PROJ_LIB}

about:
  home: http://github.com/Toblerity/Fiona
  PyPI: https://pypi.org/project/fiona
  summary: Fiona reads and writes spatial data files
  license: BSD-3-Clause
