package:
  name: wrapt
  version: 2.1.2
  top-level:
    - wrapt
source:
  url: https://files.pythonhosted.org/packages/source/w/wrapt/wrapt-2.1.2.tar.gz
  sha256: 3996a67eecc2c68fd47b4e3c564405a5777367adfd9b8abb58387b63ee83b21e
about:
  home: https://github.com/GrahamDumpleton/wrapt
  PyPI: https://pypi.org/project/wrapt
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD-2-Clause
