package:
  name: pyiceberg
  version: 0.10.0
  top-level:
    - pyiceberg
#build:
#script: python -m pip install . -vv --no-deps --no-build-isolation
source:
  url: https://files.pythonhosted.org/packages/source/p/pyiceberg/pyiceberg-0.10.0.tar.gz
  sha256: 2525afa5e7e5fc4e72b291f8e1cc219e982d2bda5ff17e62cd05b8d91c4139f5
about:
  home: https://py.iceberg.apache.org/
  PyPI: https://pypi.org/project/pyiceberg
  summary: Apache Iceberg is an open table format for huge analytic datasets
  license: Apache-2.0
requirements:
  run:
    # Dependencies that are needed to run the package
    - click
    - cachetools
    - fsspec
    - mmh3
    - pydantic
    - pyparsing
    - requests
    - rich
    - sortedcontainers
    - sqlalchemy
    - strictyaml
extra:
  recipe-maintainers:
    - bitsondatadev
