package:
  name: lazy_loader
  version: "0.5"
  top-level:
    - lazy_loader
source:
  url: https://files.pythonhosted.org/packages/py3/l/lazy_loader/lazy_loader-0.5-py3-none-any.whl
  sha256: ab0ea149e9c554d4ffeeb21105ac60bed7f3b4fd69b1d2360a4add51b170b005
about:
  home: https://scientific-python.org/specs/spec-0001/
  PyPI: https://pypi.org/project/lazy_loader
  summary: lazy_loader
  license: BSD-3-Clause
