package:
  name: libcst
  version: 1.8.6
  tag:
    - rust
  top-level:
    - libcst
source:
  url: https://files.pythonhosted.org/packages/source/l/libcst/libcst-1.8.6.tar.gz
  sha256: f729c37c9317126da9475bdd06a7208eb52fcbd180a6341648b45a56b4ba708b
requirements:
  run:
    - pyyaml
  executable:
    - rustup
about:
  home: https://libcst.readthedocs.io
  PyPI: https://pypi.org/project/libcst
  summary: A concrete syntax tree with AST-like properties for Python 3.0
    through 3.12 programs.
  license: Mixed, MIT, PSF, and Apache-2.0
extra:
  recipe-maintainers:
    - zsol
