package:
  name: frozenlist
  version: 1.8.0
  top-level:
    - frozenlist
source:
  url: https://files.pythonhosted.org/packages/source/f/frozenlist/frozenlist-1.8.0.tar.gz
  sha256: 3ede829ed8d842f6cd48fc7081d7a41001a56f1f38603f9d49bf3020d59a31ad
about:
  home: https://github.com/aio-libs/frozenlist
  PyPI: https://pypi.org/project/frozenlist
  summary: A list-like structure which implements
    collections.abc.MutableSequence
  license: Apache-2.0
