package:
  name: nh3
  version: 0.3.4
  tag:
    - rust
  top-level:
    - nh3
source:
  url: https://files.pythonhosted.org/packages/source/n/nh3/nh3-0.3.4.tar.gz
  sha256: 96709a379997c1b28c8974146ca660b0dcd3794f4f6d50c1ea549bab39ac6ade
requirements:
  executable:
    - rustup
about:
  home: https://nh3.readthedocs.io
  PyPI: https://pypi.org/project/nh3
  summary: Python bindings to the ammonia HTML sanitization library.
  license: MIT
