package:
  name: nh3
  version: 0.3.3
  tag:
    - rust
  top-level:
    - nh3
source:
  url: https://files.pythonhosted.org/packages/source/n/nh3/nh3-0.3.3.tar.gz
  sha256: 185ed41b88c910b9ca8edc89ca3b4be688a12cb9de129d84befa2f74a0039fee
requirements:
  executable:
    - rustup
about:
  home: https://nh3.readthedocs.io
  PyPI: https://pypi.org/project/nh3
  summary: Python bindings to the ammonia HTML sanitization library.
  license: MIT
