package:
  name: attrs
  version: 26.1.0
  top-level:
    - attr
    - attrs
source:
  sha256: c647aa4a12dfbad9333ca4e71fe62ddc36f4e63b2d260a37a8b83d2f043ac309
  url: https://files.pythonhosted.org/packages/py3/a/attrs/attrs-26.1.0-py3-none-any.whl
requirements:
  run:
    - six
about:
  home: https://www.attrs.org/
  PyPI: https://pypi.org/project/attrs
  summary: Classes Without Boilerplate
  license: MIT
