package:
  name: river
  version: 0.23.0
  _disabled: true # 0.23.0 not yet compatible with Python 3.14
  tag:
    - rust
  top-level:
    - river
source:
  url: https://files.pythonhosted.org/packages/source/r/river/river-0.23.0.tar.gz
  sha256: f174cb8e5984be1a193827faf8e09a03ceb110a055290628accc72ec987390f1
requirements:
  executable:
    - rustup
  host:
    - numpy
  run:
    - numpy
    - pandas
    - scipy
test:
  imports:
    - river
    - river.api
about:
  home: https://github.com/online-ml/river
  PyPI: https://pypi.org/project/river
  summary: Online machine learning in Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - MaxHalford
