package:
  name: awkward-cpp
  version: "47"
  top-level:
    - awkward_cpp

source:
  url: https://files.pythonhosted.org/packages/78/e3/5a255643d0ffdd1b2c8e53c4e0376a073f0547b85daa18f20cefa14bd90f/awkward_cpp-47.tar.gz
  sha256: 676cf4976810edab32187edf5a8a716af95047b9038c96d27d3be44f1331950f

build:
  exports: requested
  backend-flags: |
    cmake.define.CMAKE_MODULE_LINKER_FLAGS=-Wl,-rpath=\$ORIGIN
    build.verbose=ON

requirements:
  run:
    - numpy

test:
  imports:
    - awkward_cpp
    - awkward_cpp.lib._ext

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agoose77
