package:
  name: awkward-cpp
  version: "52"
  top-level:
    - awkward_cpp

source:
  url: https://files.pythonhosted.org/packages/source/a/awkward_cpp/awkward_cpp-52.tar.gz
  sha256: ef141eb20544df261b973c986cfae57be329022061be86817506add676597275

build:
  vendor-sharedlib: false # done by the package itself
  exports: requested
  backend-flags: |
    cmake.define.CMAKE_MODULE_LINKER_FLAGS=-Wl,-rpath=\$ORIGIN
    build.verbose=ON

requirements:
  run:
    - numpy

test:
  imports:
    - awkward_cpp
    - awkward_cpp.lib._ext

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agoose77
