package:
  name: xyzservices
  version: 2026.3.0
  top-level:
    - xyzservices
source:
  sha256: d226866a5d8e9fef337034d8da37a8298f0a1d9d1489b4018e69579eb321fea4
  url: https://files.pythonhosted.org/packages/source/x/xyzservices/xyzservices-2026.3.0.tar.gz
about:
  home: https://github.com/geopandas/xyzservices
  PyPI: https://pypi.org/project/xyzservices
  summary: Source of XYZ tiles providers
  license: BSD-3-Clause
