package:
  name: tomli
  version: 2.4.1
  top-level:
    - tomli
source:
  url: https://files.pythonhosted.org/packages/py3/t/tomli/tomli-2.4.1-py3-none-any.whl
  sha256: 0d85819802132122da43cb86656f8d1f8c6587d54ae7dcaf30e90533028b49fe
about:
  PyPI: https://pypi.org/project/tomli
  summary: A lil' TOML parser
  license: MIT
  home: https://github.com/hukkin/tomli
