package:
  name: packaging
  version: "26.2"
  top-level:
    - packaging
source:
  sha256: ff452ff5a3e828ce110190feff1178bb1f2ea2281fa2075aadb987c2fb221661
  url: https://files.pythonhosted.org/packages/source/p/packaging/packaging-26.2.tar.gz
  patches:
    - patches/0001-Add-backwards-compatibility-for-wheels-with-pyodide-.patch
about:
  home: https://github.com/pypa/packaging
  PyPI: https://pypi.org/project/packaging
  summary: Core utilities for Python packages
  license: BSD-2-Clause or Apache-2.0
