package:
  name: anyio
  version: 4.13.0
  top-level:
    - anyio
source:
  url: https://files.pythonhosted.org/packages/py3/a/anyio/anyio-4.13.0-py3-none-any.whl
  sha256: 08b310f9e24a9594186fd75b4f73f4a4152069e3853f1ed8bfbf58369f4ad708
requirements:
  run:
    - sniffio
    - typing-extensions
about:
  home:
  PyPI: https://pypi.org/project/anyio
  summary: High level compatibility layer for multiple asynchronous event loop
    implementations
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
