package:
  name: xarray
  version: 2025.9.0

  top-level:
    - xarray
source:
  url: https://files.pythonhosted.org/packages/d5/e4/62a677feefde05b12a70a4fc9bdc8558010182a801fbcab68cb56c2b0986/xarray-2025.12.0-py3-none-any.whl
  sha256: 9e77e820474dbbe4c6c2954d0da6342aa484e33adaa96ab916b15a786181e970
requirements:
  run:
    - numpy
    - packaging
    - pandas
about:
  home: https://github.com/pydata/xarray
  PyPI: https://pypi.org/project/xarray
  summary: N-D labeled arrays and datasets in Python
  license: Apache-2.0
