package:
  name: xarray
  version: 2025.9.0

  top-level:
    - xarray
source:
  url: https://files.pythonhosted.org/packages/8d/f0/73c24457c941b8b08f7d090853e40f4b2cdde88b5da721f3f28e98df77c9/xarray-2025.9.0-py3-none-any.whl
  sha256: 79f0e25fb39571f612526ee998ee5404d8725a1db3951aabffdb287388885df0
requirements:
  run:
    - numpy
    - packaging
    - pandas
about:
  home: https://github.com/pydata/xarray
  PyPI: https://pypi.org/project/xarray
  summary: N-D labeled arrays and datasets in Python
  license: Apache-2.0
