package:
  name: optlang
  version: 1.9.0
  top-level:
    - optlang
source:
  sha256: 74aaf820dcbead6fdd09e3f1a73a5271ad7d167966e96ff526fbf4320bb13d79
  url: https://files.pythonhosted.org/packages/py2.py3/o/optlang/optlang-1.9.0-py2.py3-none-any.whl
requirements:
  run:
    - sympy
    - six
    - swiglpk
test:
  imports:
    - optlang
    - optlang.glpk_interface
    - optlang.symbolics
about:
  home: https://github.com/opencobra/optlang
  PyPI: https://pypi.org/project/optlang
  summary: Formulate optimization problems using sympy expressions and solve
    them using interfaces to third-party optimization software (e.g. GLPK).
  license: Apache-2.0
