package:
  name: orjson
  version: 3.11.7
  tag:
    - rust
  top-level:
    - orjson
source:
  url: https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.11.7.tar.gz
  sha256: 9b1a67243945819ce55d24a30b59d6a168e86220452d2c96f4d1f093e71c0c49
requirements:
  executable:
    - rustup
about:
  home: https://github.com/ijl/orjson
  PyPI: https://pypi.org/project/orjson
  summary: Fast, correct Python JSON library supporting dataclasses, datetimes,
    and numpy
  license: Apache-2.0 OR MIT
extra:
  recipe-maintainers:
    - spicy-sauce
