package:
  name: imageio
  version: 2.37.3
  top-level:
    - imageio
source:
  sha256: 46f5bb8522cd421c0f5ae104d8268f569d856b29eb1a13b92829d1970f32c9f0
  url: https://files.pythonhosted.org/packages/py3/i/imageio/imageio-2.37.3-py3-none-any.whl
requirements:
  run:
    - numpy
    - Pillow
about:
  home: https://github.com/imageio/imageio
  PyPI: https://pypi.org/project/imageio
  summary: Library for reading and writing a wide range of image, video,
    scientific, and volumetric data formats.
  license: BSD-2-Clause
