package:
  name: mypy
  version: 1.19.1
  top-level:
    - mypyc
    - mypy
source:
  url: https://files.pythonhosted.org/packages/source/m/mypy/mypy-1.19.1.tar.gz
  sha256: 19d88bb05303fe63f71dd2c6270daca27cb9401c4ca8255fe50d1d920e0eb9ba
build:
  script: |
    export MYPY_USE_MYPYC=1
    export MYPYC_OPT_LEVEL=3
requirements:
  run:
    - librt
  constraint:
    # mypy 1.19.1 requires pathspec < 1.0.0
    - pathspec < 1.0.0
about:
  home: http://www.mypy-lang.org/
  PyPI: https://pypi.org/project/mypy
  summary: Optional static typing for Python
  license: MIT
