package:
  name: polars
  version: 1.33.1
  top-level:
    - polars
source:
  url: https://github.com/xlwings/polars-pyodide/releases/download/polars-1.33.1-pyodide-314.0.0a1/polars-1.33.1-cp314-cp314-pyemscripten_2026_0_wasm32.whl
  sha256: 3bbe58ed3c0251c65cff0b6b334ac25bd1b9c7d4d7f42e87b49ab193ce11da13
about:
  home: https://pola.rs/
  PyPI: https://pypi.org/project/polars
  summary: Blazingly fast DataFrame library
  license: MIT
extra:
  recipe-maintainers:
    - georgestagg
    - ritchie46
