package:
  name: polars
  version: 1.39.3
  _disabled: true # update to 2026_0
  top-level:
    - polars
source:
  url: https://files.pythonhosted.org/packages/py3/p/polars/polars-1.39.3-py3-none-any.whl
  sha256: c2b955ccc0a08a2bc9259785decf3d5c007b489b523bf2390cf21cec2bb82a56
about:
  home: https://pola.rs/
  PyPI: https://pypi.org/project/polars
  summary: Blazingly fast DataFrame library
  license: MIT
extra:
  recipe-maintainers:
    - georgestagg
    - ritchie46
