package:
  name: polars
  version: 1.33.1
  _disabled: true  # update to 2026_0
  top-level:
    - polars
source:
  url: https://github.com/xlwings/polars-pyodide/releases/download/polars-1.33.1-pyodide-0.29.3/polars-1.33.1-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: 61482e83d4fd43795dfe0cb0a80fa94e84a19b3e867fd10418e4cba6e18c2e78
about:
  home: https://pola.rs/
  PyPI: https://pypi.org/project/polars
  summary: Blazingly fast DataFrame library
  license: MIT
extra:
  recipe-maintainers:
    - georgestagg
    - ritchie46
