package:
  name: ewah_bool_utils
  version: 1.3.0
  top-level:
    - ewah_bool_utils
source:
  url: https://files.pythonhosted.org/packages/source/e/ewah_bool_utils/ewah_bool_utils-1.3.0.tar.gz
  sha256: 5768183dc723149bc8e9d6181d93bf69825f643034622cc275d919afb5f84668
requirements:
  run:
    - numpy
  host:
    - numpy
about:
  home: https://github.com/yt-project/ewah_bool_utils
  PyPI: https://pypi.org/project/ewah_bool_utils
  summary: EWAH Bool Array utils for yt
  license: BSD-3-Clause
