package:
  name: bilby.cython
  version: 0.5.3
  top-level:
    - docs
    - bilby_cython
source:
  url: https://files.pythonhosted.org/packages/source/b/bilby_cython/bilby_cython-0.5.3.tar.gz
  sha256: 44400b2abc6fa592b13d69f33460cb156d6edb48a783f5539ee0a21e1d0a3508
requirements:
  host:
    - numpy
  run:
    - numpy
about:
  home: https://git.ligo.org/colm.talbot/bilby-cython
  PyPI: https://pypi.org/project/bilby.cython
  summary: Optimized functionality for Bilby
  license: MIT
extra:
  recipe-maintainers:
    - colmtalbot
