package:
  name: ruamel.yaml
  version: 0.19.1
  top-level:
    - ruamel
source:
  url: https://files.pythonhosted.org/packages/py3/r/ruamel_yaml/ruamel_yaml-0.19.1-py3-none-any.whl
  sha256: 27592957fedf6e0b62f281e96effd28043345e0e66001f97683aa9a40c667c93
test:
  imports:
    - ruamel.yaml
about:
  home: https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree
  PyPI: https://pypi.org/project/ruamel.yaml
  summary: ruamel.yaml is a YAML parser/emitter that supports roundtrip
    preservation of comments, seq/map flow style, and map key order
  license: MIT
