package:
  name: h3
  version: 4.4.2
  top-level:
    - h3
source:
  url: https://files.pythonhosted.org/packages/source/h/h3/h3-4.4.2.tar.gz
  sha256: b25ab9f339e40b10dcb5e2e6988d07672e780a4950d79c25380d308cdf14f82f
about:
  home: https://uber.github.io/h3-py/
  PyPI: https://pypi.org/project/h3
  summary: Uber's hierarchical hexagonal geospatial indexing system
  license: Apache-2.0
extra:
  recipe-maintainers:
    - isaacbrodsky
    - ajfriend
