package:
  name: iniconfig
  version: 2.3.0
  top-level:
    - iniconfig
source:
  url: https://files.pythonhosted.org/packages/py3/i/iniconfig/iniconfig-2.3.0-py3-none-any.whl
  sha256: f631c04d2c48c52b84d0d0549c99ff3859c98df65b3101406327ecc7d53fbf12
about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  PyPI: https://pypi.org/project/iniconfig
  summary: "iniconfig: brain-dead simple config-ini parsing"
  license: MIT
