package:
  name: iniconfig
  version: 2.1.0
  top-level:
    - iniconfig
source:
  url: https://files.pythonhosted.org/packages/2c/e1/e6716421ea10d38022b952c159d5161ca1193197fb744506875fbb87ea7b/iniconfig-2.1.0-py3-none-any.whl
  sha256: 9deba5723312380e77435581c6bf4935c94cbfab9b1ed33ef8d238ea168eb760
about:
  home: http://github.com/RonnyPfannschmidt/iniconfig
  PyPI: https://pypi.org/project/iniconfig
  summary: "iniconfig: brain-dead simple config-ini parsing"
  license: MIT
