package:
  name: pyxel
  version: 2.6.1
  tag:
    - rust
source:
  url: https://github.com/kitao/pyxel/raw/refs/tags/v2.6.1/wasm/pyxel-2.6.1-cp38-abi3-emscripten_4_0_9_wasm32.whl
  sha256: 2dd73c5c03e9dcc60d1ae3ae07cc16d0e9f35a1a1e3aad8f3c5e9352e9496b73
# build:
#   script: |
#     embuilder build sdl2 --pic
#     export RUSTFLAGS="\
#       $RUSTFLAGS \
#       -C link-arg=-sUSE_SDL=2 \
#       -C link-arg=-lSDL2 \
#     "

requirements:
  executable:
    - rustup
test:
  imports:
    - pyxel
about:
  home: https://github.com/kitao/pyxel
  PyPI: https://pypi.org/project/pyxel/
  summary: A retro game engine for Python
  license: MIT
