package:
  name: pyxel
  version: 1.9.10
  tag:
    - rust
source:
  url: https://github.com/kitao/pyxel/archive/refs/tags/v1.9.10.tar.gz
  sha256: a5bda19aeae4a16f551aa33ac8406072ebb4d5a15e9f5552a18abe3e7db81663
build:
  script: |
    embuilder build sdl2 --pic
    export RUSTFLAGS="\
      $RUSTFLAGS \
      -C link-arg=-sUSE_SDL=2 \
      -C link-arg=-lSDL2 \
    "

requirements:
  executable:
    - rustup
  constraint:
    - maturin < 1.8
test:
  imports:
    - pyxel
about:
  home: https://github.com/kitao/pyxel
  PyPI: https://pypi.org/project/pyxel/
  summary: A retro game engine for Python
  license: MIT
