package:
  name: pyxel
  version: 1.9.10
  tag:
    - rust
source:
  url: https://github.com/kitao/pyxel/archive/refs/tags/v2.6.1.tar.gz
  sha256: 10430b66cb79892e4d0b60602e1bb1872a334145402ea842cd29c493729857b9
build:
  script: |
    embuilder build sdl2 --pic
    export RUSTFLAGS="\
      $RUSTFLAGS \
      -C link-arg=-sUSE_SDL=2 \
      -C link-arg=-lSDL2 \
    "

requirements:
  executable:
    - rustup
test:
  imports:
    - pyxel
about:
  home: https://github.com/kitao/pyxel
  PyPI: https://pypi.org/project/pyxel/
  summary: A retro game engine for Python
  license: MIT
