package:
  name: gmpy2
  version: 2.3.0
  pinned: true
  top-level:
    - gmpy2
source:
  url: https://files.pythonhosted.org/packages/source/g/gmpy2/gmpy2-2.3.0.tar.gz
  sha256: 2d943cc9051fcd6b15b2a09369e2f7e18c526bc04c210782e4da61b62495eb4a

requirements:
  host:
    - libmpc

build:
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
about:
  home: https://github.com/gmpy2/gmpy2
  PyPI: https://pypi.org/project/gmpy2
  summary: Python interface to GMP/MPIR, MPFR, and MPC
  license: LGPL-3.0+
