package:
  name: sourmash
  version: 4.9.2
  tag:
    - rust
  top-level:
    - sourmash
requirements:
  run:
    - screed
    - cffi
    - deprecation
    - cachetools
    - numpy
    - matplotlib
    - scipy
    - sqlite3
    - bitstring
  executable:
    - rustup
source:
  url: https://files.pythonhosted.org/packages/3e/1e/8cb657ac1cffa6a374a413877ef3e3ecef105035fe8a7cbe583000ecdcb8/sourmash-4.9.2.tar.gz
  sha256: 3f7d2dcecfea5dec109ee04c11d3b8b558fead6c95bd5d20ed49c810f5898dcb
about:
  home: https://github.com/sourmash-bio/sourmash
  PyPI: https://pypi.org/project/sourmash
  summary: tools for comparing biological sequences with k-mer sketches
  license: BSD-3-Clause
