package:
  name: sourmash
  version: 4.9.3
  tag:
    - rust
  top-level:
    - sourmash
requirements:
  run:
    - screed
    - cffi
    - deprecation
    - cachetools
    - numpy
    - matplotlib
    - scipy
    - sqlite3
    - bitstring
  executable:
    - rustup
source:
  url: https://pypi.org/packages/source/s/sourmash/sourmash-${{ version }}.tar.gz
  sha256: bd23e4ae4caefe3a425f2bb1feefb87757674a432eff8e77a3c0932a693a9576
about:
  home: https://github.com/sourmash-bio/sourmash
  PyPI: https://pypi.org/project/sourmash
  summary: Quickly search, compare, and analyze genomic and metagenomic data sets.
  license: BSD-3-Clause
