package:
  name: sourmash
  version: 4.9.4
  tag:
    - rust
  top-level:
    - sourmash
requirements:
  run:
    - screed
    - cffi
    - deprecation
    - cachetools
    - numpy
    - matplotlib
    - scipy
    - sqlite3
    - bitstring
  executable:
    - rustup
source:
  url: https://files.pythonhosted.org/packages/source/s/sourmash/sourmash-4.9.4.tar.gz
  sha256: 28889d11041e398831875c7d17a367e3e5937b095d006752e45c7f2302f4626d
  patches:
    - patches/0001-Bump-maturin.patch
about:
  home: https://github.com/sourmash-bio/sourmash
  PyPI: https://pypi.org/project/sourmash
  summary: Compute and compare MinHash signatures for DNA data sets.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - luizirber
    - bluegenes
    - ctb
