package:
  name: mmh3
  version: 5.2.1
source:
  url: https://files.pythonhosted.org/packages/source/m/mmh3/mmh3-5.2.1.tar.gz
  sha256: bbea5b775f0ac84945191fb83f845a6fd9a21a03ea7f2e187defac7e401616ad
about:
  PyPI: https://pypi.org/project/mmh3
  home: https://github.com/hajimes/mmh3
  summary: Python extension for MurmurHash (MurmurHash3), a set of fast and
    robust hash functions.
  license: MIT
extra:
  recipe-maintainers:
    - bitsondatadev
