package:
  name: xxhash
  version: 3.6.0
  top-level:
    - xxhash
source:
  url: https://files.pythonhosted.org/packages/source/x/xxhash/xxhash-3.6.0.tar.gz
  sha256: f0162a78b13a0d7617b2845b90c763339d1f1d82bb04a4b07f4ab535cc5e05d6
about:
  home: https://github.com/ifduyue/python-xxhash
  PyPI: https://pypi.org/project/xxhash
  summary: Python binding for xxHash
  license: BSD-2-Clause
extra:
  recipe-maintainers:
    - ifduyue
