package:
  name: certifi
  version: 2025.7.14
  top-level:
    - certifi
source:
  url: https://files.pythonhosted.org/packages/4f/52/34c6cf5bb9285074dc3531c437b3919e825d976fde097a7a73f79e726d03/certifi-2025.7.14-py3-none-any.whl
  sha256: 6b31f564a415d79ee77df69d757bb49a5bb53bd9f756cbbe24394ffd6fc1f4b2
about:
  home: https://github.com/certifi/python-certifi
  PyPI: https://pypi.org/project/certifi
  summary:
    Certifi provides Mozilla’s carefully curated collection of Root Certificates
    for validating the trustworthiness of SSL certificates while verifying the identity
    of TLS hosts.
  license: MPL-2.0
