package:
  name: certifi
  version: 2026.4.22
  top-level:
    - certifi
source:
  url: https://files.pythonhosted.org/packages/22/30/7cd8fdcdfbc5b869528b079bfb76dcdf6056b1a2097a662e5e8c04f42965/certifi-2026.4.22-py3-none-any.whl
  sha256: 3cb2210c8f88ba2318d29b0388d1023c8492ff72ecdde4ebdaddbb13a31b1c4a
about:
  home: https://github.com/certifi/python-certifi
  PyPI: https://pypi.org/project/certifi
  summary:
    Certifi provides Mozilla’s carefully curated collection of Root Certificates
    for validating the trustworthiness of SSL certificates while verifying the identity
    of TLS hosts.
  license: MPL-2.0
