package:
  name: certifi
  version: 2025.10.5
  top-level:
    - certifi
source:
  url: https://files.pythonhosted.org/packages/e4/37/af0d2ef3967ac0d6113837b44a4f0bfe1328c2b9763bd5b1744520e5cfed/certifi-2025.10.5-py3-none-any.whl
  sha256: 0f212c2744a9bb6de0c56639a6f68afe01ecd92d91f14ae897c4fe7bbeeef0de
about:
  home: https://github.com/certifi/python-certifi
  PyPI: https://pypi.org/project/certifi
  summary:
    Certifi provides Mozilla’s carefully curated collection of Root Certificates
    for validating the trustworthiness of SSL certificates while verifying the identity
    of TLS hosts.
  license: MPL-2.0
