package:
  name: reboundx
  version: 4.6.1
  top-level:
    - reboundx
build:
  exports: requested
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include/rebound/
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib/
source:
  url: https://files.pythonhosted.org/packages/source/r/reboundx/reboundx-4.6.1.tar.gz
  sha256: 2bc265c71d2600920429240494ab57be6bd5257cd226c619e49d7c62f578a442
requirements:
  run:
    - rebound
    - numpy
  host:
    - rebound
about:
  home: https://github.com/dtamayo/reboundx
  PyPI: https://pypi.org/project/reboundx
  summary: A library for including additional forces in REBOUND
  license: GPL-3.0
extra:
  recipe-maintainers:
    - hannorein
