package:
  name: fastcan
  version: 0.4.1
  top-level:
  - fastcan
source:
  url: https://files.pythonhosted.org/packages/source/f/fastcan/fastcan-0.4.1.tar.gz
  sha256: a4d3b285671920ed413462a4a3536794f494cd4373501a68f6820e1ecb151fbe
requirements:
  run:
    - scikit-learn
test:
  imports:
    - fastcan
about:
  home: https://github.com/scikit-learn-contrib/fastcan
  PyPI: https://pypi.org/project/fastcan
  summary: A fast canonical-correlation-based greedy search algorithm
  license: MIT
extra:
  recipe-maintainers:
    - MatthewSZhang
