package:
  name: rpds-py
  version: 0.28.0
  tag:
    - rust
  top-level:
    - rpds
source:
  url: https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-0.28.0.tar.gz
  sha256: abd4df20485a0983e2ca334a216249b6186d6e3c1627e106651943dbdb791aea
requirements:
  executable:
    - rustup
about:
  home: https://rpds.readthedocs.io
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
