package:
  name: rpds-py
  version: 0.30.0
  tag:
    - rust
  top-level:
    - rpds
source:
  url: https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-0.30.0.tar.gz
  sha256: dd8ff7cf90014af0c0f787eea34794ebf6415242ee1d6fa91eaba725cc441e84
requirements:
  executable:
    - rustup
about:
  home: https://rpds.readthedocs.io
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT
