package:
  name: screed
  version: 1.2.0
  top-level:
    - screed
source:
  url: https://files.pythonhosted.org/packages/f4/5f/578ead50879d1f524e4c25c54b3b9f09e1fcda0477267fe82b3aa154dab3/screed-1.2.0.tar.gz
  sha256: 0e4e6ae1f3c3cb40976bbbc2be7e191821616666e5f78406c40ce2cbfd23aad7
about:
  home: https://github.com/dib-lab/screed
  PyPI: https://pypi.org/project/screed
  summary: a Python library for loading FASTA and FASTQ sequences
  license: BSD-3-Clause
