package:
  name: starlette
  version: 1.0.0
  top-level:
    - starlette
source:
  url: https://files.pythonhosted.org/packages/py3/s/starlette/starlette-1.0.0-py3-none-any.whl
  sha256: d3ec55e0bb321692d275455ddfd3df75fff145d009685eb40dc91fc66b03d38b
about:
  home: https://github.com/encode/starlette
  PyPI: https://pypi.org/project/starlette
  summary: The little ASGI library that shines.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - hoodmane
