package:
  name: httpx
  version: 0.28.1
  # Built from a fork
  pinned: true
  top-level:
    - httpx

source:
  # Until the PR for emscripten support gets merged, build it from the PR source
  url: https://github.com/hoodmane/httpx/archive/refs/tags/pyodide_release_5.zip
  sha256: 9dcde42335d322312040f3e8c38c09976d991345b12be5ede71b65764f91a99b

test:
  imports:
    - httpx

about:
  home: https://https://github.com/encode/httpx/
  PyPI: https://pypi.org/project/httpx
  summary: A next generation HTTP client for Python.
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - joemarshall
