package:
  name: pandas
  version: 2.3.2
  tag:
    - min-scipy-stack
  top-level:
    - pandas
source:
  url: https://files.pythonhosted.org/packages/source/p/pandas/pandas-2.3.2.tar.gz
  sha256: ab7b58f8f82706890924ccdfb5f48002b83d2b5a3845976a9fb705d36c34dcdb
build:
  cflags:
    -Werror=implicit-function-declaration -Werror=mismatched-parameter-types
    -Werror=mismatched-return-types -Oz
  ldflags: --Wl,--fatal-warnings -Oz
requirements:
  host:
    - numpy
  run:
    - numpy
    - python-dateutil
    - pytz
about:
  home: https://pandas.pydata.org
  PyPI: https://pypi.org/project/pandas
  summary: Powerful data structures for data analysis, time series, and statistics
  license: BSD-3-Clause
