package:
  name: pandas
  version: 2.3.3
  tag:
    - min-scipy-stack
  top-level:
    - pandas
source:
  url: https://files.pythonhosted.org/packages/source/p/pandas/pandas-2.3.3.tar.gz
  sha256: e05e1af93b977f7eafa636d043f9f94c7ee3ac81af99c13508215942e64c993b
build:
  cflags:
    -Werror=implicit-function-declaration -Werror=mismatched-parameter-types
    -Werror=mismatched-return-types -Oz
  ldflags: --Wl,--fatal-warnings -Oz
requirements:
  host:
    - numpy
  run:
    - numpy
    - python-dateutil
    - pytz
about:
  home: https://pandas.pydata.org
  PyPI: https://pypi.org/project/pandas
  summary: Powerful data structures for data analysis, time series, and statistics
  license: BSD-3-Clause
