package:
  name: pandas
  version: 2.3.0
  tag:
    - min-scipy-stack
  top-level:
    - pandas
source:
  url: https://files.pythonhosted.org/packages/source/p/pandas/pandas-2.3.0.tar.gz
  sha256: 34600ab34ebf1131a7613a260a61dbe8b62c188ec0ea4c296da7c9a06b004133
build:
  cflags:
    -Werror=implicit-function-declaration -Werror=mismatched-parameter-types
    -Werror=mismatched-return-types -Oz
  ldflags: --Wl,--fatal-warnings -Oz
requirements:
  host:
    - numpy
  run:
    - numpy
    - python-dateutil
    - pytz
about:
  home: https://pandas.pydata.org
  PyPI: https://pypi.org/project/pandas
  summary: Powerful data structures for data analysis, time series, and statistics
  license: BSD-3-Clause
