package:
  name: numpy-tests
  version: 2.2.5
  tag:
    - min-scipy-stack
  top-level:
    - numpy
source:
  path: ../numpy/numpy-2.2.5/build

build:
  unvendor-tests: false # we do this on our own using Meson's install tags
  # numpy uses vendored meson, so we need to pass the cross file manually
  backend-flags: |
    setup-args=-Dallow-noblas=true
    setup-args=--cross-file=${MESON_CROSS_FILE}
    install-args=--tags=tests
    build-dir=build
  # Replace 'name = "numpy"' with 'name = "numpy-tests"' in pyproject.toml
  script: |
    sed -i 's/name = "numpy"/name = "numpy-tests"/' pyproject.toml
  # numpy creates numpy/distutils/__pycache__ directory during the build.
  # It breaks our test because there is a .pyc in the directory.
  post: |
    rm -rf numpy/distutils/__pycache__
  cflags: |
    -Wno-return-type
# We need NumPy to be built before we can reuse the persistent build dir
requirements:
  host:
    - numpy
about:
  home: https://www.numpy.org
  PyPI: https://pypi.org/project/numpy
  summary: NumPy is the fundamental package for array computing with Python.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agriyakhetarpal
