package:
  name: fsspec
  version: 2026.3.0
  top-level:
    - fsspec
source:
  url: https://files.pythonhosted.org/packages/py3/f/fsspec/fsspec-2026.3.0-py3-none-any.whl
  sha256: d2ceafaad1b3457968ed14efa28798162f1638dbb5d2a6868a2db002a5ee39a4
about:
  home: http://github.com/fsspec/filesystem_spec
  PyPI: https://pypi.org/project/fsspec
  summary: File-system specification
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - joemarshall
