package:
  name: gsw
  version: 3.6.21
  top-level:
    - gsw
source:
  url: https://files.pythonhosted.org/packages/source/g/gsw/gsw-3.6.21.tar.gz
  sha256: 6e0609d374916b4393484b9c7b32666d36dda74d900a40d19c766484ac295efa

requirements:
  run:
    - numpy
  host:
    - numpy

about:
  home: https://github.com/TEOS-10/GSW-python
  PyPI: https://pypi.org/project/gsw
  summary: Gibbs Seawater Oceanographic Package of TEOS-10
  license: BSD-3-Clause
