package:
  name: aiosignal
  version: 1.4.0
  top-level:
    - aiosignal
source:
  url: https://files.pythonhosted.org/packages/py3/a/aiosignal/aiosignal-1.4.0-py3-none-any.whl
  sha256: 053243f8b92b990551949e63930a839ff0cf0b0ebbe0597b0f3fb19e1a0fe82e

requirements:
  run:
    - frozenlist

about:
  home: https://github.com/aio-libs/aiosignal
  PyPI: https://pypi.org/project/aiosignal
  summary: "aiosignal: a list of registered asynchronous callbacks"
  license: Apache-2.0
