package:
  name: ujson
  version: 5.10.0
  top-level:
    - ujson
source:
  url: https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.10.0.tar.gz
  sha256: b3cd8f3c5d8c7738257f1018880444f7b7d9b66232c64649f562d7ba86ad4bc1
about:
  home: https://github.com/ultrajson/ultrajson
  PyPI: https://pypi.org/project/ujson
  summary: Ultra fast JSON encoder and decoder for Python
  license: BSD-2-Clause
extra:
  recipe-maintainers:
    - greateggsgreg
