package:
  name: ujson
  version: 5.11.0
  top-level:
    - ujson
source:
  url: https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.11.0.tar.gz
  sha256: e204ae6f909f099ba6b6b942131cee359ddda2b6e4ea39c12eb8b991fe2010e0
about:
  home: https://github.com/ultrajson/ultrajson
  PyPI: https://pypi.org/project/ujson
  summary: Ultra fast JSON encoder and decoder for Python
  license: BSD-2-Clause
extra:
  recipe-maintainers:
    - greateggsgreg
