package:
  name: retrying
  version: 1.4.2
  top-level:
    - retrying
source:
  sha256: d102e75d53d8d30b88562d45361d6c6c934da06fab31bd81c0420acb97a8ba39
  url: https://files.pythonhosted.org/packages/source/r/retrying/retrying-1.4.2.tar.gz
requirements:
  run:
    - six
about:
  home: https://github.com/rholder/retrying
  PyPI: https://pypi.org/project/retrying
  summary: Retrying
  license: Apache-2.0
