package:
  name: msgspec
  version: 0.20.0
  top-level:
    - msgspec
source:
  sha256: 692349e588fde322875f8d3025ac01689fead5901e7fb18d6870a44519d62a29
  url: https://files.pythonhosted.org/packages/source/m/msgspec/msgspec-0.20.0.tar.gz
about:
  home: https://jcristharif.com/msgspec
  PyPI: https://pypi.org/project/msgspec
  summary: A fast serialization and validation library, with builtin support for
    JSON, MessagePack, YAML, and TOML.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - bollwyvl
