package:
  name: fonttools
  version: 4.62.1
  top-level:
    - fontTools
source:
  url: https://files.pythonhosted.org/packages/py3/f/fonttools/fonttools-4.62.1-py3-none-any.whl
  sha256: 7487782e2113861f4ddcc07c3436450659e3caa5e470b27dc2177cade2d8e7fd
about:
  home: http://github.com/fonttools/fonttools
  PyPI: https://pypi.org/project/fontTools
  summary: Tools to manipulate font files
  license: MIT
