package:
  name: rich
  version: 14.3.3
  top-level:
    - rich
source:
  url: https://files.pythonhosted.org/packages/py3/r/rich/rich-14.3.3-py3-none-any.whl
  sha256: 793431c1f8619afa7d3b52b2cdec859562b950ea0d4b6b505397612db8d5362d
about:
  home: https://github.com/Textualize/rich
  PyPI: https://pypi.org/project/rich
  summary: Render rich text, tables, progress bars, syntax highlighting,
    markdown and more to the terminal
  license: MIT
extra:
  recipe-maintainers:
    - bitsondatadev
