package:
  name: smart-open
  version: 7.5.1
  top-level:
    - smart_open
source:
  url: https://files.pythonhosted.org/packages/py3/s/smart_open/smart_open-7.5.1-py3-none-any.whl
  sha256: 3e07cbbd9c8a908bcb8e25d48becf1a5cbb4886fa975e9f34c672ed171df2318
requirements:
  run:
    - wrapt
about:
  home: https://github.com/piskvorky/smart_open
  PyPI: https://pypi.org/project/smart_open
  summary: Utils for streaming large files (S3, HDFS, GCS, Azure Blob Storage,
    gzip, bz2...)
  license: MIT
