package:
  name: healpy
  version: 1.19.0
  top-level:
    - healpy
source:
  url: https://files.pythonhosted.org/packages/source/h/healpy/healpy-1.19.0.tar.gz
  sha256: 28e839cb885a23d36c77fc3423a3cb9271a07fda94085bd12fc329f941130ec5
  patches:
    - patches/0001-build-no-binaries.patch
    - patches/0002-without-zlib-check-fortran.patch
    - patches/0003-install-path.patch
requirements:
  host:
    - libzlib
  run:
    - numpy
    - astropy
build:
  vendor-sharedlib: true
  exports: requested
  cflags: |
    -I$(WASM_LIBRARY_DIR)/include
    -fwasm-exceptions
  cxxflags: |
    -fwasm-exceptions
  ldflags: |
    -fwasm-exceptions
  script: |
    export CXXFLAGS="$CXXFLAGS -sRELOCATABLE=1"
about:
  home: https://github.com/healpy/healpy
  PyPI: https://pypi.org/project/healpy
  summary: Healpix tools package for Python
  license: GPL-2.0-only
extra:
  recipe-maintainers:
    - juntyr
