package:
  name: inspice
  version: 1.7.0.5
  top-level:
    - InSpice
source:
  url: https://files.pythonhosted.org/packages/py3/i/inspice/inspice-1.7.0.5-py3-none-any.whl
  sha256: 7c4c0ce6b9c9610380285859bc93858a4ef73c7c079522683832d5be4bfdc8f8
requirements:
  run:
    - numpy
    - matplotlib
    - pyyaml
    - cffi
    - diskcache
    - h5py
    - ply
    - libngspice
about:
  home: https://github.com/Innovoltive/InSpice
  PyPI: https://pypi.org/project/inspice
  summary: Python interface to Ngspice and Xyce circuit simulators (forked from
    PySpice)
  license: GPL-3.0-or-later
extra:
  recipe-maintainers:
    - pepijndevos
