package:
  name: inspice
  version: 1.7.0.1
  top-level:
    - InSpice
source:
  url: https://files.pythonhosted.org/packages/py3/i/inspice/inspice-1.7.0.1-py3-none-any.whl
  sha256: fb2d94f96e22830ffdf8e5d104b2c904f7a7382d9b4b1f23bb871d02a2ed4bef
requirements:
  run:
    - numpy
    - matplotlib
    - pyyaml
    - cffi
    - diskcache
    - h5py
    - ply
    - libngspice
about:
  home: https://github.com/Innovoltive/InSpice
  PyPI: https://pypi.org/project/inspice
  summary: Python interface to Ngspice and Xyce circuit simulators (forked from
    PySpice)
  license: GPL-3.0-or-later
extra:
  recipe-maintainers:
    - pepijndevos
