package:
  name: pplpy
  version: 0.9.0
  top-level:
    - ppl
source:
  url: https://files.pythonhosted.org/packages/source/p/pplpy/pplpy-0.9.0.tar.gz
  sha256: 8289c50d680ce3f9eacac666cb4cdbbd8a711959e7cc7cf06f7fdb4035d0cc5d
requirements:
  host:
    - libgmp
    - libppl
    - gmpy2
  run:
    - gmpy2
    - cysignals
  constraint:
    # ImportError: cysignals.signals does not export expected C function _do_raise_exception
    - cysignals < 1.12.6
build:
  cxxflags: |
    -std=c++11
    -I$(WASM_LIBRARY_DIR)/include
  ldflags: |
    -L$(WASM_LIBRARY_DIR)/lib
about:
  home: https://github.com/sagemath/pplpy
  PyPI: https://pypi.org/project/pplpy
  summary: Python PPL wrapper
  license: GPL-3.0
extra:
  recipe-maintainers:
    - mkoeppe
