package:
  name: bleach
  version: 6.3.0
  top-level:
    - bleach
requirements:
  run:
    - webencodings
    - packaging
    - six
source:
  sha256: fe10ec77c93ddf3d13a73b035abaac7a9f5e436513864ccdad516693213c65d6
  url: https://files.pythonhosted.org/packages/py3/b/bleach/bleach-6.3.0-py3-none-any.whl
about:
  home: https://github.com/mozilla/bleach
  PyPI: https://pypi.org/project/bleach
  summary: An easy safelist-based HTML-sanitizing tool.
  license: Apache-2.0
