package:
  name: jsonschema
  version: 4.26.0
  top-level:
    - jsonschema
source:
  url: https://files.pythonhosted.org/packages/py3/j/jsonschema/jsonschema-4.26.0-py3-none-any.whl
  sha256: d489f15263b8d200f8387e64b4c3a75f06629559fb73deb8fdfb525f2dab50ce
requirements:
  run:
    - attrs
    - pyrsistent
    - referencing
    - jsonschema_specifications
about:
  home: https://github.com/Julian/jsonschema
  PyPI: https://pypi.org/project/jsonschema
  summary: An implementation of JSON Schema validation for Python
  license: MIT
