package:
  name: openai
  version: 2.30.0
  top-level:
    - openai
source:
  url: https://files.pythonhosted.org/packages/py3/o/openai/openai-2.30.0-py3-none-any.whl
  sha256: 9a5ae616888eb2748ec5e0c5b955a51592e0b201a11f4262db920f2a78c5231d
requirements:
  run:
    - httpx
    - pydantic
    - typing-extensions
    - distro
    - anyio
    - jiter
about:
  home: ""
  PyPI: https://pypi.org/project/openai
  summary: The official Python library for the openai API
  license: ""
extra:
  recipe-maintainers:
    - hoodmane
