package:
  name: zarr
  version: 3.2.1
  top-level:
    - zarr
source:
  sha256: 71565b738a0e7e8ed226f0516eba8c6bb53440ad7669a8c48ebb3534a161d035
  url: https://files.pythonhosted.org/packages/source/z/zarr/zarr-3.2.1.tar.gz
  patches:
    - 0001-Add-WASM-compatible-sync-for-Pyodide.patch
    - 0002-Set-threading.max_workers-1-on-WASM-in-config.patch
    - 0003-Fix-exclusive-atomic-writes-on-Emscripten.patch
requirements:
  run:
    - numpy
    - packaging
    - numcodecs
    - google-crc32c
    - donfig
    - typing-extensions
about:
  home: https://github.com/zarr-developers/zarr-python
  PyPI: https://pypi.org/project/zarr
  summary: An implementation of chunked, compressed, N-dimensional arrays for Python
  license: MIT
