package:
  name: parso
  version: 0.8.6
  top-level:
    - parso
source:
  sha256: 2c549f800b70a5c4952197248825584cb00f033b29c692671d3bf08bf380baff
  url: https://files.pythonhosted.org/packages/py2.py3/p/parso/parso-0.8.6-py2.py3-none-any.whl
about:
  home: https://github.com/davidhalter/parso
  PyPI: https://pypi.org/project/parso
  summary: A Python Parser
  license: MIT
