package:
  name: rateslib
  version: 2.7.0
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/22/9d/032eb3ee109e997a280351516781d17014a8e35061ad6626c6a6ac14bd3f/rateslib-2.7.0.tar.gz
  sha256: 30f7d81a479af0da821d7ee7f1c4a4de4f7643a526ba0568357d8a564f2a2099
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.7.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: LicenseRef-Rateslib-Dual
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
