package:
  name: rateslib
  version: 2.5.0
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/06/8f/309374844f2862bbbeb2fc9485599a06631fd67ec13384f127016b95b725/rateslib-2.5.0.tar.gz
  sha256: 324d6b6f49c08d70d688017d2caad368a7cf16f878f0a2fff5b7f9a7b1e3836b
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.5.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: CC-BY-NC-ND-4.0
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
