package:
  name: rateslib
  version: 2.1.1
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/5e/b0/6dda0cc0e2f215e2555035f85929544564d16c462fd7a3243b18a4307c7a/rateslib-2.1.1.tar.gz 
  sha256: 3960cba921eae7e49a51a115588d232cca8a3a8870d5c12c3b1c33cc54b5f9f0
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.1.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: CC-BY-NC-ND-4.0
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
