package:
  name: rateslib
  version: 2.0.1
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/a9/1d/2b81d88424095f48b67416440e93621981da3059d9feb97b33bbe6e5d71a/rateslib-2.0.1.tar.gz 
  sha256: 07c08fad1de9b74eb142d4ad526a2023905d2038e4ad2eacc49fbaa3bed41483
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.0.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: CC-BY-NC-ND-4.0
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
