package:
  name: rateslib
  version: 2.5.1
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/2b/d1/e20f7b1d0ee2a4468c6d4cd80d291adc231e87db0e0cff6aec70b34c469f/rateslib-2.5.1.tar.gz
  sha256: b12bc5609ee3a769fa4f965ef55eb47da061bddac80dca6cac2c5df3bebbf0a9
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.5.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: LicenseRef-Rateslib-Dual
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
