package:
  name: rateslib
  version: 2.7.1
  tag:
    - rust
  top-level:
    - rateslib
source:
  url: https://files.pythonhosted.org/packages/c0/7a/67e4cae285dfaf41d5027cf79771eb7fc18d6b2971a2800895c9c2238a25/rateslib-2.7.1.tar.gz
  sha256: b4007e57c29581aa6f7c235cda06754d0afedde4817336032cd88a5c1b7a72d8
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
  executable:
    - rustup
about:
  home: https://rateslib.com/py/en/2.7.x/
  PyPI: https://pypi.org/project/rateslib
  summary: A fixed income library for trading interest rates
  license: LicenseRef-Rateslib-Dual
extra:
  recipe-maintainers:
    - NickAltmann
    - attack68
