package:
  name: pillow-heif
  version: 1.0.0
  top-level:
    - pillow_heif
source:
  url: https://files.pythonhosted.org/packages/87/c4/cd02132eb24aab8dc50ad16b04c8761024cc77af6dfb6ddfc51ea828e9a8/pillow_heif-1.0.0.tar.gz
  sha256: 0df7a1fb29bd55bc77fd286195eeb02604e356a5da3d5e8786129b91263b99e2
  # patches:
  #   - patches/0001-Remove-include-path-check.patch
requirements:
  run:
    - cffi
    - Pillow
    - libheif
  host:
    - cffi
    - libheif
build:
  script: |
    export LIBHEIF_ROOT=${WASM_LIBRARY_DIR}
test:
  imports:
    - pillow_heif
about:
  home: https://github.com/bigcat88/pillow_heif
  PyPI: https://pypi.org/project/pillow_heif
  summary: Python 3.6+ interface to libheif library
  license: LGPL-2.1
# Note: this package needs to be manually upgraded to the next version
