package:
  name: pillow-heif
  version: 1.1.0
  top-level:
    - pillow_heif
source:
  url: https://files.pythonhosted.org/packages/6f/d4/597cf8c54d1ed494a46cc12e358d2f73a993b5f139402b35681f56beffde/pillow_heif-1.1.0.tar.gz
  sha256: 6c0c5f81a780185bbddc56e0d5537c53aa6cb5fb6018f5a60534a47c53f5455d
  # patches:
  #   - patches/0001-Remove-include-path-check.patch
requirements:
  run:
    - cffi
    - Pillow
    - libheif
  host:
    - cffi
    - libheif
build:
  script: |
    export LIBHEIF_ROOT=${WASM_LIBRARY_DIR}
test:
  imports:
    - pillow_heif
about:
  home: https://github.com/bigcat88/pillow_heif
  PyPI: https://pypi.org/project/pillow_heif
  summary: Python 3.6+ interface to libheif library
  license: LGPL-2.1
# Note: this package needs to be manually upgraded to the next version
