package:
  name: pillow-heif
  version: 1.1.1
  top-level:
    - pillow_heif
source:
  url: https://files.pythonhosted.org/packages/source/p/pillow_heif/pillow_heif-1.1.1.tar.gz
  sha256: f60e8c8a8928556104cec4fff39d43caa1da105625bdb53b11ce3c89d09b6bde
requirements:
  run:
    - cffi
    - Pillow
  host:
    - cffi
    - libheif
build:
  vendor_sharedlib: true
  script: |
    export LIBHEIF_ROOT=${WASM_LIBRARY_DIR}
test:
  imports:
    - pillow_heif
about:
  home: https://github.com/bigcat88/pillow_heif
  PyPI: https://pypi.org/project/pillow_heif
  summary: Python 3.6+ interface to libheif library
  license: LGPL-2.1
# Note: this package needs to be manually upgraded to the next version
