package:
  name: charset-normalizer
  version: 3.4.4
  top-level:
    - charset_normalizer
source:
  url: https://files.pythonhosted.org/packages/0a/4c/925909008ed5a988ccbb72dcc897407e5d6d3bd72410d69e051fc0c14647/charset_normalizer-3.4.4-py3-none-any.whl
  sha256: 7a32c560861a02ff789ad905a2fe94e3f840803362c84fecf1851cb4cf3dc37f
about:
  home: https://github.com/Ousret/charset_normalizer
  PyPI: https://pypi.org/project/charset-normalizer
  summary:
    The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
  license: MIT
