package:
  name: charset-normalizer
  version: 3.4.2
  top-level:
    - charset_normalizer
source:
  url: https://files.pythonhosted.org/packages/20/94/c5790835a017658cbfabd07f3bfb549140c3ac458cfc196323996b10095a/charset_normalizer-3.4.2-py3-none-any.whl
  sha256: 7f56930ab0abd1c45cd15be65cc741c28b1c9a34876ce8c17a2fa107810c0af0
about:
  home: https://github.com/Ousret/charset_normalizer
  PyPI: https://pypi.org/project/charset-normalizer
  summary:
    The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
  license: MIT
