package:
  name: boost-histogram
  version: 1.7.1
  top-level:
    - boost_histogram
source:
  url: https://files.pythonhosted.org/packages/source/b/boost_histogram/boost_histogram-1.7.1.tar.gz
  sha256: 6ed3d7d2688fa32889dd441a7ef4920d60d696137d2abc3ab14eb9bd3b455b19
requirements:
  run:
    - numpy # runtime only
about:
  home: https://github.com/scikit-hep/boost-histogram
  PyPI: https://pypi.org/project/boost-histogram
  summary: The Boost::Histogram Python wrapper.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - henryiii
