package:
  name: boost-histogram
  version: 1.6.1
  pinned: true
  top-level:
    - boost_histogram
source:
  url: https://files.pythonhosted.org/packages/0e/85/eb1db36e997997677fe5ac12ef33a5149c2438b6f8afe7aa256baaa784c6/boost_histogram-1.6.1.tar.gz
  sha256: cbe67507f62063590395cc9fe177bf979f26a53c0574365f8241b883b9a6f756
requirements:
  run:
    - numpy # runtime only
about:
  home: https://github.com/scikit-hep/boost-histogram
  PyPI: https://pypi.org/project/boost-histogram
  summary: The Boost::Histogram Python wrapper.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - henryiii
