package:
  name: boost-histogram
  version: 1.7.0
  top-level:
    - boost_histogram
source:
  url: https://files.pythonhosted.org/packages/source/b/boost_histogram/boost_histogram-1.7.0.tar.gz
  sha256: 51ce2d84223078c3164bd733a23cd1b6b3e687a9c6dca0b73be54d0a70f62b64
requirements:
  run:
    - numpy # runtime only
about:
  home: https://github.com/scikit-hep/boost-histogram
  PyPI: https://pypi.org/project/boost-histogram
  summary: The Boost::Histogram Python wrapper.
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - henryiii
