package:
  name: bitstring
  version: 4.3.1
  top-level:
    - bitstring
source:
  url: https://files.pythonhosted.org/packages/75/2d/174566b533755ddf8efb32a5503af61c756a983de379f8ad3aed6a982d38/bitstring-4.3.1-py3-none-any.whl
  sha256: 69d1587f0ac18dc7d93fc7e80d5f447161a33e57027e726dc18a0a8bacf1711a
requirements:
  run:
    - bitarray
about:
  home: https://github.com/scott-griffiths/bitstring
  PyPI: https://pypi.org/project/bitstring
  summary: Simple construction, analysis and modification of binary data.
  license: MIT
