package:
  name: libflint
  version: 3.2.2
  tag:
    - library
    - static_library
source:
  url: https://github.com/flintlib/flint/releases/download/v3.2.2/flint-3.2.2.tar.gz
  sha256: 577d7729e4c2e79ca1e894ad2ce34bc73516a92f623d42562694817f888a17eb
requirements:
  host:
    - libgmp
    - libmpfr

build:
  type: static_library
  script: |
    emconfigure ./configure \
        CFLAGS="-fPIC" \
        --disable-dependency-tracking \
        --disable-shared \
        --prefix=${WASM_LIBRARY_DIR} \
        --with-gmp=${WASM_LIBRARY_DIR} \
        --with-mpfr=${WASM_LIBRARY_DIR} \
        --host=wasm32-unknown-emscripten \
        --disable-assembly \
        --disable-pthread
    emmake make -j ${PYODIDE_JOBS:-3}
    emmake make install
about:
  home: https://flintlib.org/
  license: GPL-3.0 OR LGPL-3.0
