package:
  name: zstandard
  version: 0.25.0
  top-level:
    - zstandard
source:
  url: https://files.pythonhosted.org/packages/source/z/zstandard/zstandard-0.25.0.tar.gz
  sha256: 7713e1179d162cf5c7906da876ec2ccb9c3a9dcbdffef0cc7f70c3667a205f0b
requirements:
  host:
    - cffi
    - setuptools
  run:
    - cffi
about:
  home: https://github.com/indygreg/python-zstandard
  PyPI: https://pypi.org/project/zstandard
  summary: Zstandard bindings for Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agriyakhetarpal
