package:
  name: patsy
  version: 1.0.2
  top-level:
    - patsy
source:
  url: https://files.pythonhosted.org/packages/source/p/patsy/patsy-1.0.2.tar.gz
  sha256: cdc995455f6233e90e22de72c37fcadb344e7586fb83f06696f54d92f8ce74c0
requirements:
  run:
    - numpy
    - six
about:
  home: https://github.com/pydata/patsy
  PyPI: https://pypi.org/project/patsy
  summary: A Python package for describing statistical models and for building
    design matrices.
  license: BSD-2-Clause
