package:
  name: msprime
  version: 1.4.1
  top-level:
    - msprime
source:
  url: https://files.pythonhosted.org/packages/source/m/msprime/msprime-1.4.1.tar.gz
  sha256: 68a7208eaea30ca473365287c833078f654af1e186b24fc0105e7717c93bb967
build:
  script: |
    export LIBGSL_INCLUDE_PATH=$(pkg-config --cflags-only-I --dont-define-prefix gsl)
    export LIBGSL_LIBRARY_PATH=$(pkg-config --libs-only-L --dont-define-prefix gsl)
  cflags: |
    $(LIBGSL_INCLUDE_PATH)
  ldflags: |
    $(LIBGSL_LIBRARY_PATH)
requirements:
  run:
    - numpy
    - newick
    - tskit
    - demes
    - rpds-py
  host:
    - libgsl
    - numpy
about:
  home: https://tskit.dev/msprime
  PyPI: https://pypi.org/project/msprime
  summary: Simulate genealogical trees and genomic sequence data using
    population genetic models
  license: GPL-3.0+
