package:
  name: msprime
  version: 1.4.0
  top-level:
    - msprime
source:
  url: https://files.pythonhosted.org/packages/source/m/msprime/msprime-1.4.0.tar.gz
  sha256: 6a409765db3a5d40dcac024a3ae8966698b45050f13fe8e823c8124f750883bf
build:
  script: |
    export LIBGSL_INCLUDE_PATH=$(pkg-config --cflags-only-I --dont-define-prefix gsl)
    export LIBGSL_LIBRARY_PATH=$(pkg-config --libs-only-L --dont-define-prefix gsl)
  cflags: |
    $(LIBGSL_INCLUDE_PATH)
  ldflags: |
    $(LIBGSL_LIBRARY_PATH)
requirements:
  run:
    - numpy
    - newick
    - tskit
    - demes
    - rpds-py
  host:
    - libgsl
    - numpy
about:
  home: https://tskit.dev/msprime
  PyPI: https://pypi.org/project/msprime
  summary:
    Simulate genealogical trees and genomic sequence data using population
    genetic models
  license: GPL-3.0+
