package:
  name: idna
  version: "3.11"
  top-level:
    - idna
source:
  url: https://files.pythonhosted.org/packages/py3/i/idna/idna-3.11-py3-none-any.whl
  sha256: 771a87f49d9defaf64091e6e6fe9c18d4833f140bd19464795bc32d966ca37ea
about:
  home: https://github.com/kjd/idna
  PyPI: https://pypi.org/project/idna
  summary: Internationalized Domain Names in Applications (IDNA)
  license: BSD-3-Clause
