package:
  name: sqlalchemy
  version: 2.0.48
  top-level:
    - sqlalchemy
source:
  url: https://files.pythonhosted.org/packages/source/s/sqlalchemy/sqlalchemy-2.0.48.tar.gz
  sha256: 5ca74f37f3369b45e1f6b7b06afb182af1fd5dde009e4ffd831830d98cbe5fe7
requirements:
  run:
    - typing-extensions
about:
  home: https://www.sqlalchemy.org
  PyPI: https://pypi.org/project/sqlalchemy
  summary: Database Abstraction Library
  license: MIT
