package:
  name: apsw
  version: 3.51.3.0
  top-level:
    - apsw
source:
  url: https://files.pythonhosted.org/packages/source/a/apsw/apsw-3.51.3.0.tar.gz
  sha256: 821966a66ed5fd539e863a8f60d9a53497e0a47ffdabde4ec7714fae9ed00261
test:
  imports:
    - apsw
about:
  home: https://github.com/rogerbinns/apsw
  PyPI: https://pypi.org/project/apsw
  summary: Another Python SQLite Wrapper
  license: any-OSI
extra:
  recipe-maintainers:
    - airen1986
