package:
  name: peewee
  version: 4.0.4
  top-level:
    - peewee
requirements:
  host:
    - cffi
    - cffi
source:
  url: https://files.pythonhosted.org/packages/source/p/peewee/peewee-4.0.4.tar.gz
  sha256: 70e07c14a10bec8d663514bda5854e44ef15d5b03974b41f7218066b6fd3a065
about:
  home: https://github.com/coleifer/peewee/
  PyPI: https://pypi.org/project/peewee/
  summary: Peewee is a simple and small ORM. It has few (but expressive)
    concepts, making it easy to learn and intuitive to use.
  license: MIT
