package:
  name: jiter
  version: 0.11.1
  top-level:
    - jiter
source:
  url: https://files.pythonhosted.org/packages/source/j/jiter/jiter-0.11.1.tar.gz
  sha256: 849dcfc76481c0ea0099391235b7ca97d7279e0fa4c86005457ac7c88e8b76dc
about:
  home: https://github.com/pydantic/jiter/tree/main/crates/jiter-python
  PyPI: https://pypi.org/project/jiter
  summary: Fast, safe JSON parser written in Rust with support for parsing
    partial JSON
  license: MIT
extra:
  recipe-maintainers:
    - samuelcolvin
