package:
  name: statsmodels
  version: 0.14.6
  top-level:
    - statsmodels
source:
  url: https://files.pythonhosted.org/packages/source/s/statsmodels/statsmodels-0.14.6.tar.gz
  sha256: 4d17873d3e607d398b85126cd4ed7aad89e4e9d89fc744cdab1af3189a996c2a

build:
  ldflags: |
    -L$(NUMPY_LIB)/core/lib/
    -L$(NUMPY_LIB)/random/lib/
  unvendor-tests: false # for better testing
requirements:
  host:
    - numpy
    - scipy
    - setuptools
  run:
    - numpy
    - scipy
    - pandas
    - patsy
    - packaging

test:
  imports:
    - statsmodels
    - statsmodels.api
about:
  home: https://www.statsmodels.org/
  PyPI: https://pypi.org/project/statsmodels
  summary: Statistical computations and models for Python
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - agriyakhetarpal
