package:
  name: cachetools
  version: 7.0.5
  top-level:
    - cachetools
source:
  url: https://files.pythonhosted.org/packages/py3/c/cachetools/cachetools-7.0.5-py3-none-any.whl
  sha256: 46bc8ebefbe485407621d0a4264b23c080cedd913921bad7ac3ed2f26c183114
about:
  home: https://github.com/tkem/cachetools/
  PyPI: https://pypi.org/project/cachetools
  summary: Extensible memoizing collections and decorators
  license: MIT
