package:
  name: Cartopy
  version: 0.25.0
  top-level:
    - cartopy
source:
  url: https://files.pythonhosted.org/packages/3c/3f/ec3dee34237b696a486d566a6d3ae6550ae821836e0412bafdcbbec2cfd2/cartopy-0.25.0.tar.gz
  sha256: 55f1a390e5f3f075b221c7d91fb10258ad978db786c7930eba06eb45d28753fe
test:
  imports:
    - cartopy
    - cartopy.trace
    - cartopy.mpl.geoaxes
    - cartopy.crs
requirements:
  host:
    - libgeos
    - numpy
  run:
    - shapely
    - pyshp
    - pyproj
    - libgeos
    - matplotlib
    - scipy

build:
  vendor-sharedlib: true
  script: |
    # Put geos-config on the path
    export PATH=$PATH:${WASM_LIBRARY_DIR}/bin/

about:
  home: http://scitools.org.uk/cartopy
  PyPI: https://pypi.org/project/Cartopy/
  summary: A library providing cartographic tools for python
  license: LGPL-3.0+
