package:
  name: prompt_toolkit
  version: 3.0.52
  top-level:
    - prompt_toolkit
source:
  url: https://files.pythonhosted.org/packages/py3/p/prompt_toolkit/prompt_toolkit-3.0.52-py3-none-any.whl
  sha256: 9aac639a3bbd33284347de5ad8d68ecc044b91a762dc39b7c21095fcd6a19955
requirements:
  run:
    - wcwidth
about:
  home: https://github.com/prompt-toolkit/python-prompt-toolkit
  PyPI: https://pypi.org/project/prompt_toolkit
  summary: Library for building powerful interactive command lines in Python
  license: BSD-3-Clause
