package:
  name: langsmith
  version: 0.4.13
  top-level:
    - langsmith
source:
  url: https://files.pythonhosted.org/packages/py3/l/langsmith/langsmith-0.4.13-py3-none-any.whl
  sha256: dab7b16ee16986995007bf5a777f45c18f8bf7453f67ae2ebcb46ce43c214297
about:
  home: https://smith.langchain.com/
  PyPI: https://pypi.org/project/langsmith
  summary: Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.
  license: MIT
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
requirements:
  run:
    - requests
    - typing-extensions
    - pydantic
test:
  imports:
    - langsmith
    - langsmith.client
