package:
  name: plotly
  version: 6.3.0
  top-level:
    - _plotly_utils
    - plotly
source:
  url: https://files.pythonhosted.org/packages/95/a9/12e2dc726ba1ba775a2c6922d5d5b4488ad60bdab0888c337c194c8e6de8/plotly-6.3.0-py3-none-any.whl
  sha256: 7ad806edce9d3cdd882eaebaf97c0c9e252043ed1ed3d382c3e3520ec07806d4

requirements:
  run:
    - packaging
    - numpy
    - pandas
    - requests
    - retrying
    - tenacity
    - narwhals
    - six
    - python-dateutil
    - idna
    - charset-normalizer
    - certifi
    - urllib3

test:
  imports:
    - plotly
    - plotly.graph_objects
    - plotly.express
    - plotly.io
about:
  home: null
  PyPI: https://pypi.org/project/plotly
  summary: An open-source interactive data visualization library for Python
  license: MIT
