package:
  name: plotly
  version: 6.3.0
  top-level:
    - _plotly_utils
    - plotly
source:
  url: https://files.pythonhosted.org/packages/95/a9/12e2dc726ba1ba775a2c6922d5d5b4488ad60bdab0888c337c194c8e6de8/plotly-6.3.0-py3-none-any.whl
  sha256: 7ad806edce9d3cdd882eaebaf97c0c9e252043ed1ed3d382c3e3520ec07806d4

requirements:
  run:
    - packaging
    - numpy
    - pandas
    - requests
    - retrying
    - tenacity
    - narwhals
    - six
    - python-dateutil
    - idna
    - charset-normalizer
    - certifi
    - urllib3

test:
  imports:
    - plotly
    - plotly.graph_objects
    - plotly.express
    - plotly.io
about:
  home: null
  PyPI: https://pypi.org/project/plotly
  summary: An open-source interactive data visualization library for Python
  license:
    "MIT License\n        \n        Copyright (c) 2016-2024 Plotly Technologies
    Inc.\n        \n        Permission is hereby granted, free of charge, to any person
    obtaining a copy\n        of this software and associated documentation files
    (the \"Software\"), to deal\n        in the Software without restriction, including
    without limitation the rights\n        to use, copy, modify, merge, publish, distribute,
    sublicense, and/or sell\n        copies of the Software, and to permit persons
    to whom the Software is\n        furnished to do so, subject to the following
    conditions:\n        \n        The above copyright notice and this permission
    notice shall be included in\n        all copies or substantial portions of the
    Software.\n        \n        THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY
    OF ANY KIND, EXPRESS OR\n        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY,\n        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE\n        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
    CLAIM, DAMAGES OR OTHER\n        LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM,\n        OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN\n        THE SOFTWARE.\n        "
