package:
  name: narwhals
  version: 2.15.0
  top-level:
    - narwhals
source:
  url: https://files.pythonhosted.org/packages/py3/n/narwhals/narwhals-2.15.0-py3-none-any.whl
  sha256: cbfe21ca19d260d9fd67f995ec75c44592d1f106933b03ddd375df7ac841f9d6
about:
  home: https://github.com/narwhals-dev/narwhals
  PyPI: https://pypi.org/project/narwhals
  summary: Extremely lightweight compatibility layer between dataframe libraries
  license: MIT
extra:
  recipe-maintainers:
    - MarcoGorelli
