package:
  name: narwhals
  version: 2.13.0
  top-level:
    - narwhals
source:
  url: https://files.pythonhosted.org/packages/py3/n/narwhals/narwhals-2.13.0-py3-none-any.whl
  sha256: 9b795523c179ca78204e3be53726da374168f906e38de2ff174c2363baaaf481
about:
  home: https://github.com/narwhals-dev/narwhals
  PyPI: https://pypi.org/project/narwhals
  summary: Extremely lightweight compatibility layer between dataframe libraries
  license: MIT
extra:
  recipe-maintainers:
    - MarcoGorelli
