package:
  name: narwhals
  version: 2.17.0
  top-level:
    - narwhals
source:
  url: https://files.pythonhosted.org/packages/py3/n/narwhals/narwhals-2.17.0-py3-none-any.whl
  sha256: 2ac5307b7c2b275a7d66eeda906b8605e3d7a760951e188dcfff86e8ebe083dd
about:
  home: https://github.com/narwhals-dev/narwhals
  PyPI: https://pypi.org/project/narwhals
  summary: Extremely lightweight compatibility layer between dataframe libraries
  license: MIT
extra:
  recipe-maintainers:
    - MarcoGorelli
