package:
  name: argon2-cffi-bindings
  version: 25.1.0
  top-level:
    - _argon2_cffi_bindings
source:
  url: https://files.pythonhosted.org/packages/source/a/argon2_cffi_bindings/argon2_cffi_bindings-25.1.0.tar.gz
  sha256: b957f3e6ea4d55d820e40ff76f450952807013d361a65d7f28acc0acbf29229d
requirements:
  run:
    - cffi
build:
  cflags: -mrelaxed-simd
extra:
  recipe-maintainers:
    - alarmfox
about:
  home: https://github.com/hynek/argon2-cffi-bindings
  PyPI: https://pypi.org/project/argon2-cffi-bindings
  summary: Low-level CFFI bindings for Argon2
  license: MIT
