package:
  name: python-calamine
  version: 0.5.3
  top-level:
    - python_calamine
source:
  url: https://files.pythonhosted.org/packages/source/p/python_calamine/python_calamine-0.5.3.tar.gz
  sha256: b4529c955fa64444184630d5bc8c82c472d1cf6bfe631f0a7bfc5e4802d4e996
requirements:
  run:
    - packaging
  executable:
    - rustup
about:
  home: https://github.com/dimastbk/python-calamine
  PyPI: https://pypi.org/project/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file -
    calamine
  license: MIT
extra:
  recipe-maintainers:
    - airen1986
