package:
  name: python-calamine
  version: 0.4.0
  top-level:
    - python_calamine
source:
  url: https://files.pythonhosted.org/packages/source/p/python_calamine/python_calamine-0.4.0.tar.gz
  sha256: 94afcbae3fec36d2d7475095a59d4dc6fae45829968c743cb799ebae269d7bbf
requirements:
  run:
    - packaging
  executable:
    - rustup
about:
  home: https://github.com/dimastbk/python-calamine
  PyPI: https://pypi.org/project/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file -
    calamine
  license: MIT
extra:
  recipe-maintainers:
    - airen1986
