package:
  name: python-calamine
  version: 0.6.2
  top-level:
    - python_calamine
source:
  url: https://files.pythonhosted.org/packages/source/p/python_calamine/python_calamine-0.6.2.tar.gz
  sha256: 2c90e5224c5e92db9fcd8f22b6085ce63b935cfe7a893ac9a1c3c56793bafd9d
requirements:
  run:
    - packaging
  executable:
    - rustup
about:
  home: https://github.com/dimastbk/python-calamine
  PyPI: https://pypi.org/project/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file -
    calamine
  license: MIT
extra:
  recipe-maintainers:
    - airen1986
