package:
  name: wcwidth
  version: 0.6.0
  top-level:
    - wcwidth
source:
  url: https://files.pythonhosted.org/packages/py3/w/wcwidth/wcwidth-0.6.0-py3-none-any.whl
  sha256: 1a3a1e510b553315f8e146c54764f4fb6264ffad731b3d78088cdb1478ffbdad
about:
  home: https://github.com/jquast/wcwidth
  PyPI: https://pypi.org/project/wcwidth
  summary: Measures the displayed width of unicode strings in a terminal
  license: MIT
