package:
  name: h11
  version: 0.16.0
  top-level:
    - h11
source:
  url: https://files.pythonhosted.org/packages/py3/h/h11/h11-0.16.0-py3-none-any.whl
  sha256: 63cf8bbe7522de3bf65932fda1d9c2772064ffb3dae62d55932da54b31cb6c86
about:
  home: https://github.com/python-hyper/h11
  PyPI: https://pypi.org/project/h11
  summary: A pure-Python, bring-your-own-I/O implementation of HTTP/1.1
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
