package:
  name: rustworkx
  version: 0.17.1
  top-level:
    - rustworkx
  tag:
    - rust
  _disabled: true # does not work with latest toolchain
source:
  url: https://files.pythonhosted.org/packages/source/r/rustworkx/rustworkx-0.17.1.tar.gz
  sha256: 59ea01b4e603daffa4e8827316c1641eef18ae9032f0b1b14aa0181687e3108e
build:
  script: |
    rustup component add rust-src
    export RUSTFLAGS="$RUSTFLAGS -C target-feature=+atomics,+bulk-memory,+mutable-globals"
requirements:
  executable:
    - rustup
test:
  imports:
    - rustworkx
about:
  home: https://github.com/Qiskit/rustworkx
  PyPI: https://pypi.org/project/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
extra:
  recipe-maintainers:
    - IvanIsCoding
