package:
  name: rustworkx
  version: 0.17.1
  top-level:
    - rustworkx
  tag:
    - rust
  _disabled: true  # does not work with latest toolchain
source:
  url: https://github.com/Qiskit/rustworkx/archive/refs/tags/0.17.1.tar.gz
  sha256: dc248da9cc364b81ac67f5d67b626ee3f03a1f6299f7a9b4d0a0501548715365
build:
  script: |
    rustup component add rust-src
    export RUSTFLAGS="$RUSTFLAGS -C target-feature=+atomics,+bulk-memory,+mutable-globals"
requirements:
  executable:
    - rustup
test:
  imports:
    - rustworkx
about:
  home: https://github.com/Qiskit/rustworkx
  PyPI: https://pypi.org/project/rustworkx
  summary: A python graph library implemented in Rust
  license: Apache-2.0
extra:
  recipe-maintainers:
    - IvanIsCoding
