package:
  name: osqp
  version: 1.1.1
  top-level:
    - osqp
requirements:
  run:
    - Jinja2
    - numpy
    - scipy
source:
  url: https://github.com/osqp/osqp-python/releases/download/v1.1.1/osqp-1.1.1-cp312-cp312-pyodide_2024_0_wasm32.whl
  sha256: aed8280cdb6d079d0c896bbe647984d34869d7fd2ef9ec5187c52762b128bc65
about:
  home: https://github.com/osqp/osqp-python
  PyPI: https://pypi.org/project/osqp
  summary: Python wrappers for OSQP
  license: Apache-2.0
extra:
  recipe-maintainers:
    - vineetbansal
