package:
  name: cloudpickle
  version: 3.1.2
  top-level:
    - cloudpickle
source:
  sha256: 9acb47f6afd73f60dc1df93bb801b472f05ff42fa6c84167d25cb206be1fbf4a
  url: https://files.pythonhosted.org/packages/py3/c/cloudpickle/cloudpickle-3.1.2-py3-none-any.whl
about:
  home: https://github.com/cloudpipe/cloudpickle
  PyPI: https://pypi.org/project/cloudpickle
  summary: Extended pickling support for Python objects
  license: BSD-3-Clause
