package:
  name: duckdb
  version: 1.5.0
  top-level:
    - duckdb
source:
  url: https://github.com/xlwings/duckdb-pyodide/releases/download/duckdb-v1.5.0-pyodide-0.29.3/duckdb-1.5.0-cp313-cp313-pyodide_2025_0_wasm32.whl
  sha256: ee14bd19e6d9a390bb2803f119d4eff06a88a8e4b52ebf6c947c9dac67f6ba11
about:
  home: https://github.com/duckdb/duckdb
  PyPI: https://pypi.org/project/duckdb
  summary: A fast in-process analytical database
  license: MIT
