package:
  name: tiktoken
  version: 0.12.0
  tag:
    - rust
  top-level:
    - tiktoken
    - tiktoken_ext
source:
  url: https://files.pythonhosted.org/packages/source/t/tiktoken/tiktoken-0.12.0.tar.gz
  sha256: b18ba7ee2b093863978fcb14f74b3707cdc8d4d4d3836853ce7ec60772139931
requirements:
  executable:
    - rustup
  run:
    - regex
    - requests
about:
  home: https://pypi.org/project/tiktoken
  PyPI: https://pypi.org/project/tiktoken
  summary: tiktoken is a fast BPE tokeniser for use with OpenAI's models
  license: MIT
extra:
  recipe-maintainers:
    - riyavsinha
