package:
  name: multidict
  version: 6.7.0
  top-level:
    - multidict
source:
  url: https://files.pythonhosted.org/packages/source/m/multidict/multidict-6.7.0.tar.gz
  sha256: c6e99d9a65ca282e578dfea819cfa9c0a62b2499d8677392e09feaf305e9e6f5
about:
  home: https://github.com/aio-libs/multidict
  PyPI: https://pypi.org/project/multidict
  summary: multidict implementation
  license: Apache-2.0
