package:
  name: multidict
  version: 6.5.0
  top-level:
    - multidict
source:
  url: https://files.pythonhosted.org/packages/46/b5/59f27b4ce9951a4bce56b88ba5ff5159486797ab18863f2b4c1c5e8465bd/multidict-6.5.0.tar.gz
  sha256: 942bd8002492ba819426a8d7aefde3189c1b87099cdf18aaaefefcf7f3f7b6d2
about:
  home: https://github.com/aio-libs/multidict
  PyPI: https://pypi.org/project/multidict
  summary: multidict implementation
  license: Apache-2.0
