package:
  name: multidict
  version: 6.6.3
  top-level:
    - multidict
source:
  url: https://files.pythonhosted.org/packages/3d/2c/5dad12e82fbdf7470f29bff2171484bf07cb3b16ada60a6589af8f376440/multidict-6.6.3.tar.gz
  sha256: 798a9eb12dab0a6c2e29c1de6f3468af5cb2da6053a20dfa3344907eed0937cc
about:
  home: https://github.com/aio-libs/multidict
  PyPI: https://pypi.org/project/multidict
  summary: multidict implementation
  license: Apache-2.0
