package:
  name: multidict
  version: 6.7.1
  top-level:
    - multidict
source:
  url: https://files.pythonhosted.org/packages/source/m/multidict/multidict-6.7.1.tar.gz
  sha256: ec6652a1bee61c53a3e5776b6049172c53b6aaba34f18c9ad04f82712bac623d
about:
  home: https://github.com/aio-libs/multidict
  PyPI: https://pypi.org/project/multidict
  summary: multidict implementation
  license: Apache-2.0
