package:
  name: texture2ddecoder
  version: 1.0.6
  top-level:
    - texture2ddecoder
source:
  url: https://files.pythonhosted.org/packages/source/t/texture2ddecoder/texture2ddecoder-1.0.6.tar.gz
  sha256: 88f04d8951018ac13b8dacd07e57e8adad4a6f1cfe5509646e8a1020346a81ca
about:
  home: https://github.com/K0lb3/texture2ddecoder
  PyPI: https://pypi.org/project/texture2ddecoder
  summary: a python wrapper for Perfare's Texture2DDecoder
  license: MIT
extra:
  recipe-maintainers:
    - greateggsgreg
