package:
  name: zengl
  version: 2.7.2
  top-level:
    - zengl
    - _zengl

source:
  url: https://files.pythonhosted.org/packages/source/z/zengl/zengl-2.7.2.tar.gz
  sha256: f5fdecb76cd0c45cc82b53f02cd90ecc4d8c742924ccee48603080d0dcb58a81

about:
  home: https://github.com/szabolcsdombi/zengl/
  PyPI: https://pypi.org/project/zengl
  summary: OpenGL Pipelines for Python
  license: MIT
extra:
  recipe-maintainers:
    - szabolcsdombi
