package:
  name: varint
  version: 1.0.2
  top-level:
    - varint
source:
  url: https://files.pythonhosted.org/packages/source/v/varint/varint-1.0.2.tar.gz
  sha256: a6ecc02377ac5ee9d65a6a8ad45c9ff1dac8ccee19400a5950fb51d594214ca5
about:
  home: http://github.com/fmoo/python-varint
  PyPI: https://pypi.org/project/varint
  summary: Simple python varint implementation
  license: MIT
