package:
  name: igraph
  version: 1.0.0
  top-level:
    - igraph

source:
  url: https://files.pythonhosted.org/packages/source/i/igraph/igraph-1.0.0.tar.gz
  sha256: 2414d0be2e4d77ee5357807d100974b40f6082bb1bb71988ec46cfb6728651ee

requirements:
  run:
    - texttable

build:
  cflags: |
    -Wno-return-type

test:
  imports:
    - igraph

about:
  home: https://igraph.org/python
  PyPI: https://pypi.org/project/igraph
  summary: High performance graph data structures and algorithms
  license: GPL-2.0
extra:
  recipe-maintainers:
    - ntamas
