package:
  name: tree-sitter
  version: 0.25.2
  top-level:
    - tree_sitter
source:
  url: https://files.pythonhosted.org/packages/66/7c/0350cfc47faadc0d3cf7d8237a4e34032b3014ddf4a12ded9933e1648b55/tree-sitter-0.25.2.tar.gz
  sha256: fe43c158555da46723b28b52e058ad444195afd1db3ca7720c59a254544e9c20
about:
  home: https://tree-sitter.github.io/tree-sitter
  PyPI: https://pypi.org/project/tree-sitter
  summary: Python bindings to the Tree-sitter parsing library
  license: MIT
extra:
  recipe-maintainers:
    - ericwb
