package:
  name: libngspice
  version: "44.2"
  tag:
    - library
    - shared_library
source:
  url: https://github.com/danchitnis/ngspice-sf-mirror/archive/refs/tags/ngspice-44.2.zip
  sha256: 3ae94703938247a22148f60a1307d52719d42a9134b5aef6252594000f513902
  patches:
    - patches/0001-keep-alive-API-functions.patch
    - patches/0001-no-hicum2.patch
    - patches/0003-fix-verilog-install-hook.patch

build:
  type: shared_library
  script: |
    bash ./autogen.sh

    # First build cmpp natively for build-time code generation
    mkdir build-native && cd build-native
    ../configure --enable-xspice --disable-debug --without-x --with-readline=no
    make -C src/xspice/cmpp -j ${PYODIDE_JOBS:-3}
    cd ..

    configure_args=(
      --prefix=${WASM_LIBRARY_DIR}
      --enable-xspice
      --disable-debug
      --disable-dependency-tracking
      --enable-cider
      --with-readline=no
      --disable-openmp
      --with-ngshared
      --host=wasm32-unknown-emscripten
    )

    mkdir release-lib && cd release-lib
    emconfigure ../configure "${configure_args[@]}" CFLAGS="${SIDE_MODULE_CFLAGS}"

    # Build everything except xspice/cmpp first
    emmake make -j ${PYODIDE_JOBS:-3} -C src/xspice/cmpp LDFLAGS="${SIDE_MODULE_LDFLAGS}"

    # Now replace the wasm cmpp with the native one and touch to prevent rebuild
    cp ../build-native/src/xspice/cmpp/cmpp src/xspice/cmpp/cmpp
    touch src/xspice/cmpp/cmpp

    # Continue building the rest
    emmake make -j ${PYODIDE_JOBS:-3} LDFLAGS="${SIDE_MODULE_LDFLAGS}"
    emmake make install
    cp ${WASM_LIBRARY_DIR}/lib/libngspice.so ${DISTDIR}

    # Copy XSPICE code model libraries to ngspice/*.cm
    # Since shared_library packages extract to /usr/lib/, the final path will be /usr/lib/ngspice/*.cm
    mkdir -p ${DISTDIR}/ngspice
    cp ${WASM_LIBRARY_DIR}/lib/ngspice/*.cm ${DISTDIR}/ngspice/

about:
  home: http://ngspice.sourceforge.net
  license: BSD-3-Clause
  summary: The open source spice simulator for electric and electronic circuits
extra:
  recipe-maintainers:
    - pepijndevos
