package:
  name: brotli
  version: 1.2.0
  top-level:
    - brotli
source:
  url: https://files.pythonhosted.org/packages/source/b/brotli/brotli-1.2.0.tar.gz
  sha256: e310f77e41941c13340a95976fe66a8a95b01e783d430eeaf7a2f87e0a57dd0a
about:
  home: https://github.com/google/brotli
  PyPI: https://pypi.org/project/brotli
  summary: Python bindings for the Brotli compression library
  license: MIT
