package:
  name: typing-extensions
  version: 4.14.1
  top-level:
    - typing_extensions
source:
  url: https://files.pythonhosted.org/packages/b5/00/d631e67a838026495268c2f6884f3711a15a9a2a96cd244fdaea53b823fb/typing_extensions-4.14.1-py3-none-any.whl
  sha256: d1e1e3b58374dc93031d6eda2420a48ea44a36c2b4766a4fdeb3710755731d76
about:
  home: https://github.com/python/typing_extensions
  license: PSF
