package:
  name: typing-extensions
  version: 4.15.0
  top-level:
    - typing_extensions
source:
  url: https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl
  sha256: f0fa19c6845758ab08074a0cfa8b7aecb71c999ca73d62883bc25cc018c4e548
about:
  home: https://github.com/python/typing_extensions
  license: PSF
