package:
  name: typing-extensions
  version: 4.14.0
  top-level:
    - typing_extensions
source:
  url: https://files.pythonhosted.org/packages/69/e0/552843e0d356fbb5256d21449fa957fa4eff3bbc135a74a691ee70c7c5da/typing_extensions-4.14.0-py3-none-any.whl
  sha256: a1514509136dd0b477638fc68d6a91497af5076466ad0fa6c338e44e359944af
about:
  home: https://github.com/python/typing_extensions
  license: PSF
