package:
  name: python-sat
  version: 1.8.dev26
  top-level:
    - pysat
source:
  sha256: 097c98aaf9b48fd19b07c5957860bfa3aae346f24d0eab9a18b1864448087e87
  url: https://files.pythonhosted.org/packages/d2/86/ba88012e81531648ba06422ba0e80c9c90cd5fd01ffcfa678567bc5bb920/python_sat-1.8.dev26.tar.gz

  patches:
    - patches/force_malloc.patch
    - patches/proper_build.patch
    - patches/dummy_buildhpp.patch

requirements:
  run:
    - six

about:
  home: https://github.com/pysathq/pysat
  PyPI: https://pypi.org/project/python-sat
  summary: A Python library for prototyping with SAT oracles
  license: MIT
extra:
  recipe-maintainers:
    - alexeyignatiev
