package:
  name: python-sat
  version: 1.8.dev19
  top-level:
    - pysat
source:
  sha256: b272f915cec08b89e3a477038492598bc9d34f1c22b1f33acc6cbd2aaf8538b3
  url: https://files.pythonhosted.org/packages/72/56/81fcad52cc1cf47399500cb0062a00094897df1bb8847cf989aaf73afc76/python_sat-1.8.dev19.tar.gz

  patches:
    - patches/force_malloc.patch
    - patches/proper_build.patch
    - patches/dummy_buildhpp.patch

requirements:
  run:
    - six

about:
  home: https://github.com/pysathq/pysat
  PyPI: https://pypi.org/project/python-sat
  summary: A Python library for prototyping with SAT oracles
  license: MIT
extra:
  recipe-maintainers:
    - alexeyignatiev
