package:
  name: pyshp
  version: 3.0.3
  top-level:
    - shapefile
source:
  url: https://files.pythonhosted.org/packages/py3/p/pyshp/pyshp-3.0.3-py3-none-any.whl
  sha256: 28c8fac8c0c25bb0fecbbfd10ead7f319c2ff2f3b0b44a94f22bd2c93510ad42
test:
  imports:
    - shapefile
about:
  home: https://github.com/GeospatialPython/pyshp
  PyPI: https://pypi.org/project/pyshp
  summary: Pure Python read/write support for ESRI Shapefile format
  license: MIT
