package:
  name: nltk
  version: 3.9.4
  top-level:
    - nltk
source:
  sha256: f2fa301c3a12718ce4a0e9305c5675299da5ad9e26068218b69d692fda84828f
  url: https://files.pythonhosted.org/packages/py3/n/nltk/nltk-3.9.4-py3-none-any.whl
requirements:
  run:
    - regex
about:
  home: https://www.nltk.org/
  PyPI: https://pypi.org/project/nltk
  summary: Natural Language Toolkit
  license: Apache-2.0
