package:
  name: mpmath
  version: 1.4.1
  top-level:
    - mpmath
source:
  sha256: dc4f0ea2304480d4a9a48a94c1020571558ade522b44a6912efac63a586e140f
  url: https://files.pythonhosted.org/packages/py3/m/mpmath/mpmath-1.4.1-py3-none-any.whl
about:
  home: http://mpmath.org/
  PyPI: https://pypi.org/project/mpmath
  summary: Python library for arbitrary-precision floating-point arithmetic
  license: BSD-3-Clause
