package:
  name: ipython
  version: 9.12.0
  top-level:
    - IPython
source:
  url: https://files.pythonhosted.org/packages/py3/i/ipython/ipython-9.12.0-py3-none-any.whl
  sha256: 0f2701e8ee86e117e37f50563205d36feaa259d2e08d4a6bc6b6d74b18ce128d
requirements:
  run:
    - asttokens
    - decorator
    - executing
    - matplotlib-inline
    - prompt_toolkit
    - pure-eval
    - Pygments
    - six
    - stack-data
    - traitlets
    - wcwidth
about:
  home: https://ipython.org
  PyPI: https://pypi.org/project/ipython
  summary: "IPython: Productive Interactive Computing"
  license: BSD-3-Clause
