package:
  name: pytest_httpx
  version: 0.36.0
  top-level:
    - pytest_httpx
source:
  url: https://files.pythonhosted.org/packages/py3/p/pytest_httpx/pytest_httpx-0.36.0-py3-none-any.whl
  sha256: bd4c120bb80e142df856e825ec9f17981effb84d159f9fa29ed97e2357c3a9c8
requirements:
  run:
    - httpx
    - pytest
    - httpcore
about:
  home: ""
  PyPI: https://pypi.org/project/pytest_httpx
  summary: Send responses to httpx.
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
