package:
  name: bokeh
  version: 3.9.0
  top-level:
    - bokeh
requirements:
  run:
    - contourpy
    - numpy
    - Jinja2
    - pandas
    - Pillow
    - python-dateutil
    - six
    - typing-extensions
    - pyyaml
    - xyzservices
source:
  sha256: 775219714a8496973ddbae16b1861606ba19fe670a421e4d43267b41148e07a3
  url: https://files.pythonhosted.org/packages/source/b/bokeh/bokeh-3.9.0.tar.gz
about:
  home: https://github.com/bokeh/bokeh
  PyPI: https://pypi.org/project/bokeh
  summary: Interactive plots and applications in the browser from Python
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - ianthomas23
