package:
  name: pyxirr
  version: 0.10.8
  tag:
    - rust
  top-level:
    - pyxirr
source:
  url: https://files.pythonhosted.org/packages/source/p/pyxirr/pyxirr-0.10.8.tar.gz
  sha256: a5620dd76015444f26f805c4983a41664898fbf2a74956a28589b171ed96d2f5
about:
  home: https://github.com/Anexen/pyxirr
  PyPI: https://pypi.org/project/pyxirr
  summary: Rust-powered collection of financial functions.
  license: Unlicense
requirements:
  executable:
    - rustup
    - cargo
extra:
  recipe-maintainers:
    - Anexen
