package:
  name: fastapi
  version: 0.135.3
  top-level:
    - fastapi
source:
  url: https://files.pythonhosted.org/packages/py3/f/fastapi/fastapi-0.135.3-py3-none-any.whl
  sha256: 9b0f590c813acd13d0ab43dd8494138eb58e484bfac405db1f3187cfc5810d98
requirements:
  run:
    - httpx
    - Jinja2
    - pydantic
    - starlette
    - anyio
about:
  home: https://github.com/fastapi/fastapi/
  PyPI: https://pypi.org/project/fastapi
  summary: FastAPI framework, high performance, easy to learn, fast to code,
    ready for production
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
