package:
  name: fastapi
  version: 0.116.1
  top-level:
    - fastapi
source:
  url: https://files.pythonhosted.org/packages/py3/f/fastapi/fastapi-0.116.1-py3-none-any.whl
  sha256: c46ac7c312df840f0c9e220f7964bada936781bc4e2e6eb71f1c4d7553786565
requirements:
  run:
    - httpx
    - Jinja2
    - pydantic
    - starlette
    - anyio
about:
  home: https://github.com/fastapi/fastapi/
  PyPI: https://pypi.org/project/fastapi
  summary:
    FastAPI framework, high performance, easy to learn, fast to code, ready
    for production
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
