package:
  name: fastapi
  version: 0.136.1
  top-level:
    - fastapi
source:
  url: https://files.pythonhosted.org/packages/py3/f/fastapi/fastapi-0.136.1-py3-none-any.whl
  sha256: a6e9d7eeada96c93a4d69cb03836b44fa34e2854accb7244a1ece36cd4781c3f
requirements:
  run:
    - httpx
    - Jinja2
    - pydantic
    - starlette
    - anyio
about:
  home: https://github.com/fastapi/fastapi/
  PyPI: https://pypi.org/project/fastapi
  summary: FastAPI framework, high performance, easy to learn, fast to code,
    ready for production
  license: MIT
extra:
  recipe-maintainers:
    - hoodmane
