package:
  name: audioop-lts
  version: 0.2.2
  top-level:
    - audioop

source:
  url: https://files.pythonhosted.org/packages/source/a/audioop_lts/audioop_lts-0.2.2.tar.gz
  sha256: 64d0c62d88e67b98a1a5e71987b7aa7b5bcffc7dcee65b635823dbdd0a8dbbd0

about:
  license: PSF-2.0

extra:
  recipe-maintainers:
    - swnf
