package:
  name: pytz
  version: "2025.2"
  tag:
    - core
    - min-scipy-stack
  top-level:
    - pytz
source:
  sha256: 5ddf76296dd8c44c26eb8f4b6f35488f3ccbf6fbbd7adee0b7262d43f0ec2f00
  url: https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl
about:
  home: http://pythonhosted.org/pytz
  PyPI: https://pypi.org/project/pytz
  summary: World timezone definitions, modern and historical
  license: MIT
