package:
  name: iminuit
  version: 2.32.0
source:
  url: https://files.pythonhosted.org/packages/source/i/iminuit/iminuit-2.32.0.tar.gz
  sha256: a32b34d18665959be75ad6bdb1dd80459bb94466c62b455631c00568accdf7d2
test:
  imports:
    - iminuit
requirements:
  run:
    - numpy # runtime only
about:
  home: http://github.com/scikit-hep/iminuit
  PyPI: https://pypi.org/project/iminuit
  summary: Jupyter-friendly Python frontend for MINUIT2 in C++
  license: Mixed MIT, LGPL-2.0
extra:
  recipe-maintainers:
    - henryiii
